### ISSUE TITLE
No more access to the history views after migrating from Plone 4.3 to 5.1

### ISSUE THREAD

**Issue by phep** [plone/Products.CMFPlone#2823] opened 2019-04-02 10:28 UTC
Hi,

I'm reporting this bug as asked by T. Kim Nguyen on StackOverflow.

I got some problems migrating to Plone 5, and that one is a real blocker.

Whatever the 5.x version I tried to migrate to from our (add-on free) 4.3.18 instance, installing and migrating to Dexterity or not, after migration I cannot use the "view history" button in the navigation portlet to display the history view of the object displayed in the main page.

Hovering (and clicking) over the button, my browser (tried with Firefox and Chromium) displays the following link :

`.../some/url/?_authenticator=....`

instead of :

`.../some/url/@@historyview?_authenticator=....`

The only way to access the history view is to edit the URL manually, adding the `@@historyview` thingie.

I could reproduced it starting from a vanilla 4.3.18 version - so this sort of put aside problems with our own instance. All instances have been deployed using their respective unified installers.

TIA,

phep

**Comment by phep** [comment] 2019-04-03 07:51
FWIW, since our goal is to update our currently in production 4.3.7 to Plone 5, I just attempted to upgrade a vanilla 4.3.7 to 5.1.5 with no avail. While there is no error during the migration process, the problem is still here : the `@@historyview` thingie is always missing when we hover/click on the clock icon in the once-green toolbar. 

I also tried to sort-of bissect it and met the same result with vanilla 4.3.10 and 4.3.14 versions.

**Comment by ida** [comment] 2019-04-04 06:40
Confirmed. Fix is to go to `[SITE_URL]/portal_actions/object/history/manage_propertiesForm` and insert `string:${object_url}/@@historyview` in the field `URL (expression)`, respectively do that programatically via a profile's `actions.xml`.

**Comment by ida** [comment] 2019-04-04 07:02
Looks like the upgrade removes this entry. A new site works fine.

**Comment by phep** [comment] 2019-04-04 11:09
Thanks @ida , this solved the problem, actually.

**Comment by jensens** [comment] 2023-03-12 17:52
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Closed by jensens** 2023-03-12 17:52 UTC
