### ISSUE TITLE
Circular dependency between Products.CMFPlone and plone.app.testing

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#327] opened 2014-12-10 12:19 UTC
Products.CMFPlone depends on plone.app.testing and vica versa.

**Comment by hvelarde** [comment] 2015-05-25 20:53
the issue is the following: suppose I want to guarantee that some version of some package is used only with some version of Plone.

I will introduce a dependency on ``CMFPlone == x.y`` and that will bring a circular dependency.

how do you solve this without doing it?

**Comment by gforcada** [comment] 2023-10-14 17:57
Probably still not fixed, as CMFPlone does not have `plone/meta` applied yet, but we can close this, as it is an integral part of applying `plone/meta` to it.

**Closed by gforcada** 2023-10-14 17:57 UTC
Labels: 99 tag: dependencies
