### ISSUE TITLE
"Insert" button not working after editing image info

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#659] opened 2015-06-29 18:53 UTC
Created a news item, added an image, saved news item. Edited news item, selected image & clicked on image icon in TinyMCE toolbar. Added image "Title" and tried to save by clicking on "Insert" button. Nothing happened. 
![hello my plone 5 site 2015-06-29 14-13-31](https://cloud.githubusercontent.com/assets/7101218/8415672/9455f4a8-1e6e-11e5-905e-c1e01b2d60e5.png)

**Comment by vangheem** [comment] 2015-06-30 03:59
Reading this more carefully I realized you're talking about something else.

I imagine you are testing on b2? I can't reproduce. What browser?

**Comment by 3dogMcNeill** [comment] 2015-06-30 14:01
Yes, v5.0b2, Firefox v38.0.5, no add-ons other than those that ship with this version. I should probably test in multiple browsers before submiting tickets?

**Comment by vangheem** [comment] 2015-06-30 14:13
No, I suspect this has already been fixed though. There was a similar bug already addressed. We need to release more often :)

**Comment by vangheem** [comment] 2015-07-02 18:13
Closing for now as I can't reproduce this on master and now there is also robot tests covering this.

**Closed by vangheem** 2015-07-02 18:13 UTC
