### ISSUE TITLE
Error after removing user with site administrator privileges

### ISSUE THREAD

**Issue by AshRaghav** [plone/Products.CMFPlone#2886] opened 2019-06-18 21:12 UTC
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Removing a user with Site Administrator permission returns insufficient privileges for folders they owned previously.

### What I did:

When a user leaves the organisation we usually remove the access on Plone as there is no way to just "deactivate" the login.

Therefore, I have removed users in the past but recently a long time employee left the firm and after removing their user ID, the folders they created returned error. 

### What I expect to happen:

I was expecting Plone to not tie down the folders to the specific author or at least when deleting a user show a prompt to say that all the files/folders owned should be migrated to another user before deleting, etc. 

None of this happened and therefore I didn't realise the impact it had.

### What actually happened:

It is simply throwing "insufficient privileges" error for all the users trying to access the folder.

### What version of Plone/ Addons I am using:

Plone 4.3.3

**Comment by mauritsvanrees** [comment] 2019-06-18 21:43
I tried it with 4.3.18 and could not reproduce this. Plone 4.3.3 is much older, but I don't suspect this is the problem.
What I did:

- Create a user and add him to the group Site Administrators.
- Login as that user and create a Folder and a Page within that Folder.
- Keep them both private.
- Create another user and give him the Reader role in the whole site.
- Remove the Site Administrator user.
- Login as the other user. He can still see both the Folder and the Page.
- Anonymous cannot see them, but that is normal, because they are private. I tried with a public folder at first, and anonymous could see that after the user was removed.

Does it go wrong for you when you try the above?

What is the review state of the item you try to see? Do you have a special workflow?

Does a user with Manager role also get the "insufficient privileges" error?

You can go to the Errors control panel and remove `Unauthorized` from the "Ignored exception types". Then try to access the content again. You should then get  an error in the Errors control panel that may put you on the right track. To get a more informative error message, you may need to switch on the [`verbose-security` development option](https://pypi.org/project/plone.recipe.zope2instance/#development-options) in your buildout instance config.

In the Zope Management Interface you can check the permissions. Login as Manager and add `/manage_access` at the end of the url of the content item.
That also has a small form where you can type the id of a user and check his roles and permissions in that context.

**Comment by AshRaghav** [comment] 2019-06-18 22:21
@mauritsvanrees - thanks for the comprehensive response. 

Yes - I get the error when I access it as a normal user and also as a Manager (and/or a site administrator).

The review state is "Private" and I am only using intranet_workflow. I have logged in as another site admin to no avail. 

The errors control panel says - You are not allowed to access 'portal_type' in this context. 

I have also double-checked my permissions in ZMI to ensure I have the highest privilege possible but I still get the same error. 

It almost feels like Plone doesn't like it when an owner who previously owned a folder gets deleted off the system. As soon as I add the user ID again to users list, the error goes away and the folder is accessible again.

Any other ideas?

Thanks again for your guidance.

**Comment by mauritsvanrees** [comment] 2021-09-30 17:12
At a customer who is with one site still on Plone 4.3.4, I saw the same error today. The sysadmin searched on the internet and found this issue. Just as in your case, they had removed a high privileged user, in this case a Manager. I tried the same locally, but did not get an error with that.

I found the problem though. Plone has a script `check_id.py`, which you can see in `portal_skins/plone_scripts`. The user with the Manager role had customized this script, so it was in `portal_skins/custom`. This meant he now had the Owner role on the script. The user was removed, and no one could edit a page anymore.

Solution: go to this script in the custom skin, go to the Ownership tab, and take ownership yourself. Then everyone can edit again.

I guess the same happened in your case. Perhaps a different script. I guess a script that only does `return "Hello world"` would not give a problem. But accessing `context.portal_type` was already too much here.
I think their site has a workflow that makes most pages not viewable for anonymous users. And it was a private page, which does not help here.
The script also has proxy roles, maybe this is a requirement for the bug to surface.

I tried in Plone 4.3.20 though with this new information, and still could not reproduce it. So I will close this issue.
But I hope this explanation sheds some light on the problem you had. :-)

**Closed by mauritsvanrees** 2021-09-30 17:12 UTC
