### ISSUE TITLE
Searchability of the folder contents view.

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#736] opened 2015-07-19 14:44 UTC
Not a bug but perhaps a thing that might be considered for a further Plone version:

People frequently use the browser search for finding something within the folder content view e.g. with large batches of items.

I suggest that build-in search functionality would be handy. In decent project we often use

https://datatables.net/

as primary interface for content listings. It can be used for large amounts of items, you can search over all items even when they are not in the current visible batch, you can add hidden texts to each item that would be search to (e.g. you would display the "title" only but provide the "description" as hidden and additional searchable text).

As said: just a thought for further work on the folder contents view...

**Comment by vangheem** [comment] 2015-07-19 17:56
So this would be different than current search in that it doesn't make an additional request to the server--it just search the currently retrieved set of items? I'm not sure how we could make the interface work with something like that along with the current search.

![screen shot 2015-07-19 at 12 53 17 pm](https://cloud.githubusercontent.com/assets/524413/8767069/3d12cba6-2e15-11e5-9885-b267e3254e68.png)

**Comment by thet** [comment] 2015-07-20 21:54
Doesn't datatables load all items in order to search them or is it querying the backend?

However, the current folder listings search already covers searching folder contents. Only maybe the portal search is a bit confusing on a page, where another search field is offered.

**Comment by djay** [comment] 2015-07-21 03:21
This is related to https://github.com/plone/Products.CMFPlone/issues/687. I think we need a place for search in the toolbar or folder contents. It's not a good idea to rely on the search being in the themed site because for some sites they might not want it.
Most likely it should be in contents because that would allow you to take actions on items in the results. Probably with a quick search popout as an item on the toolbar.

**Comment by djay** [comment] 2015-07-21 03:24
in fact it really is just a duplicate of #687 so I'll close it.

**Closed by djay** 2015-07-21 03:24 UTC
Labels: Enhancement
