### ISSUE TITLE
New content types not shown in navigation by default

### ISSUE THREAD

**Issue by hvelarde** [plone/Products.CMFPlone#1568] opened 2016-05-02 15:27 UTC
New content types are not automatically added to the **Displayed content types** list; this was not the case in Plone 4:

![selection_066](https://cloud.githubusercontent.com/assets/341393/14958428/27225120-1061-11e6-9a3d-5e47f177430c.png)

**Comment by polyester** [comment] 2016-05-03 15:10
Debatable if this is a 'regression'. For my usecases, it is a huge blessing that tons of content types are **not** automatically added, because that confuses users a lot. So for me, this is positive change rather than regression. 
Plus, explicit is better than implicit, so it would be good to have this be an explicit decision by an integrator/add-on-writer.

It is something that should be documented in the "write an add-on" part of docs.

**Comment by davilima6** [comment] 2016-05-03 16:18
Just to make things clearer, new content types _are_ added to the list. The regression is that they aren't initially checked by default, which does impact addons migration, in the form of the need of an upgrade step.

I agree with @polyester this is a better behavior since main menu and sitemap are delicate parts of every website and you usually don't want every kind of newly created items appearing, but rather just the explicitly defined ones.

It's a trade-off. But since this is a major version, if there is consensus it might be a good time to fix that (in documentation atm).

**Comment by hvelarde** [comment] 2016-05-03 17:45
@polyester while I may agree this behavior is better, unintended consequences are not the way to enhance things; I labeled it as a regression because is a different behavior from the previous version and the change is not documented anywhere.

just after a more inclusive discussion has taken place, and everybody agrees this behavior is better, we can think on it as an enhancement; then we will have to document it not only on how to write a new add-on, but also on the migration guide.

**Comment by agitator** [comment] 2018-03-07 09:32
@hvelarde can we close this issue, or is there still work to be done?

**Closed** 2018-03-07 13:33 UTC
Labels: 02 type: regression, 21 status: confirmed, 99 tag: UX Site Admin

**Comment by gforcada** [comment] 2018-03-07 13:46
We could add a warning message on the control panel though, so that users would know that the content types need to be added manually on the list of available types to add...
