### ISSUE TITLE
plone 5.0b2, fail adding archetypes 

### ISSUE THREAD

**Issue by gnafou** [plone/Products.CMFPlone#635] opened 2015-06-17 05:36 UTC
Using the unified installer to build a plone 5b02, i get the following error when clicking 'install archetypes content types for plone'

Fred

```
Traceback (innermost last):
    * Module ZPublisher.Publish, line 138, in publish
    * Module ZPublisher.mapply, line 77, in mapply
    * Module ZPublisher.Publish, line 48, in call_object
    * Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 218, in __call__
    * Module Products.GenericSetup.tool, line 365, in runAllImportStepsFromProfile
__traceback_info__: profile-Products.ATContentTypes:default
    * Module Products.GenericSetup.tool, line 1119, in _runImportStepsFromContext
    * Module Products.GenericSetup.tool, line 1030, in _doRunImportStep
__traceback_info__: typeinfo
    * Module Products.CMFCore.exportimport.typeinfo, line 225, in importTypesTool
    * Module Products.GenericSetup.utils, line 838, in importObjects
__traceback_info__: portal_types
    * Module Products.GenericSetup.utils, line 834, in importObjects
__traceback_info__: types/Collection
    * Module Products.GenericSetup.utils, line 509, in _importBody
    * Module Products.CMFCore.exportimport.typeinfo, line 60, in _importNode
    * Module Products.GenericSetup.utils, line 730, in _initProperties
ValueError: undefined property 'content_meta_type'
```

**Comment by tomgross** [comment] 2015-06-25 06:26
I have a similar issue which is probably related and probably not. Adding Archetype content gives a 404 NotFound error.

Steps to reproduce:
 1. Install any AT content type (for example content types used for testing included in Archetypes itself) in the Plone portal
 2. Create a content object (e.g. SimpleFolder) and it fails with 404-NotFound on the following URL http://localhost:8080/Plone/createObject?type_name=SimpleFolder&_authenticator=88d654f8977573a7442cb484a0ac66868b5a110c

I'm using master with last release 5.0b2

**Comment by vangheem** [comment] 2015-07-13 05:50
The reason this is failing has something to do with conflicting content type definitions already on the site.

We don't want to be able to install ATContentTypes types on Plone 5 do we? I thought existing sites would just by default continue using ATContentTypes. Also, you can run the "Archetypes-tools without content-types" product install in /portal_quickinstaller/manage_installProductsForm.

I'm afraid people will install this without knowing what it is really doing. At the very least, we hide this from the install list and move the "Archetypes-tools without content-types" to the list.

Thoughts?

**Comment by vangheem** [comment] 2015-07-13 06:57
This happens to be a duplicate of https://github.com/plone/Products.CMFPlone/issues/382

**Closed by vangheem** 2015-07-13 06:57 UTC
Labels: Bug, Sprint
