### ISSUE TITLE
Images in navigation portlet shown with improper URL

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1364] opened 2016-02-04 13:37 UTC
See screenshot taken from plone-demo.info.

It shows broken images inside the navigation portlet due to the fact the the src of the images broken. It seems to contain the physical path of the object instead of the correct address related to the VHOST.
![out](https://cloud.githubusercontent.com/assets/594239/12816432/c3110c7a-cb4c-11e5-9d19-b9e143d1f90a.png)

Tested with Plone 5.0.2

**Comment by thet** [comment] 2016-02-04 14:03
Slightly related: https://github.com/plone/Products.CMFPlone/issues/1322

**Comment by davilima6** [comment] 2016-08-08 11:28
Closed in plone/plone.app.portlets#79.

**Closed by davilima6** 2016-08-08 11:28 UTC

**Comment by fgrcon** [comment] 2016-08-08 11:41
rendered:  https://www.plone-demo.info/**plone**/images/image-5/@@images/image/icon
should be: https://www.plone-demo.info/images/image-5/@@images/image/icon

works now since: https://github.com/plone/plone.app.portlets/commit/dd25cf7333cfe3b34d73769a9f80bb05edea9630#diff-9696d73de0c15089bb62b2e4bd96d4db 
thanks @davilima6 , @jensens 
but: now renders as
 http://192.168.1.15:8080/Plone/**/Plone/**ordner-2/140-2012-09-07_img_0454.jpg/@@images/image/icon
should?: http://192.168.1.15:8080/Plone/ordner-2/140-2012-09-07_img_0454.jpg/@@images/image/icon
 (sorry  was my bug, did not test with  vikrt host)
concurrent editing :-)

**Comment by davilima6** [comment] 2016-08-08 13:58
@fgrcon: I do not get double `/Plone/Plone` without Vhost. I confess I didn't test with Vhost (is it possible to try it without Apache/ngnix?), but in my commit [I used](https://github.com/plone/plone.app.portlets/blob/master/plone/app/portlets/portlets/navigation_recurse.pt#L34) `portal_url` which I thought would be informed by VHM already.

**Comment by fgrcon** [comment] 2016-08-09 09:28
@davilima6  you'r right. The Monster does the translation ... . There is a new pull request https://github.com/plone/plone.app.portlets/pull/83 (even simpler code) which should work in both ways.
http://jenkins.plone.org/job/pull-request-5.1/529/ let's see what jenkins thinks about it :-)

I dont know, if there is a way testing vhosts without using a Web server.  I run my different plone instances on virtual machines with debian - its quite simple to configure apache or nginx ...

**Comment by davilima6** [comment] 2016-08-09 09:36
@fgrcon: I didn't understand #83. The only diff from #82 seems to be the var name (from icon_url to thumb_url) and, more importantly, the use of `node/path` instead of `node/getURL` (which I reference as ` item_url` ). The former is how it is now in master, since `imageBase` is `node/path` .

**Comment by fgrcon** [comment] 2016-08-09 10:08
@davilima6 : not quite the same: 
with node/getURL :
 I got :
...//192.168.1.15:8080/Plone/ordner-2/140-2012-09-07_img_0454.jpg**/view**/@@images/image/icon
...//ploneori.dev/Plone/ordner-2/140-2012-09-07_img_0454.jpg/**view**/@@images/image/icon

But I am somewhat confused. ,Im just doing some research myself.  I branched back to 3.1.3  with my last modifications. I still cannot reproduce the bug - it worked a as intented !!

**Comment by davilima6** [comment] 2016-08-09 11:32
I updated plone/plone.app.portlets#82 from node/getURL to node/item/getURL because the brain doesn't include the /view/ part. I _think_ it should be ok now :) (aka it seems we need to add some tests)

**Comment by fgrcon** [comment] 2016-08-09 11:48
@davilima6 :+1:  Looks great! Now there are  correct absolute paths to the thumbs (with or without vhm) which should be safe - i guess the problem was somewhere with virtual host mapping. I closed   https://github.com/plone/plone.app.portlets/pull/83
