### ISSUE TITLE
dexterity content type issue

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1130] opened 2015-10-03 12:44 UTC
i created a dexterity content type. this has only the rich text enabled. in the final view i get the title "Text" and Content Folder too getting shown. how can I remove them. pls help. pls check the screenshot. circled in red.

![dexterity issue - 3-oct2015](https://cloud.githubusercontent.com/assets/10380993/10262940/88b81018-69fa-11e5-8d18-02867e840ec4.jpg)

**Comment by gforcada** [comment] 2015-10-03 20:51
The Contents section is because a TTW dexterity content type is folderish (i.e. you can add items inside), and the title is shown, well because all content has a title...

What you probably want to do is to customize the default view for this particular content type.

**Comment by sudhan77** [comment] 2015-10-04 09:50
Page is a also a dexterity content type. Its behaviour is different. please
check.. Also there is an option to select which content types should be
included. I have selected " No content types". The display of none content
type is ok under edit view. But not in final view. the screenshot i have
sent earlier is the published view.

On Sun, Oct 4, 2015 at 2:21 AM, Gil Forcada Codinachs <
notifications@github.com> wrote:

> The Contents section is because a TTW dexterity content type is folderish
> (i.e. you can add items inside), and the title is shown, well because all
> content has a title...
>
> What you probably want to do is to customize the default view for this
> particular content type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plone/Products.CMFPlone/issues/1130#issuecomment-145288109>
> .
>



-- 
Sudhanshu

**Comment by jensens** [comment] 2015-10-05 13:48
This is a current limitation, through the web created types are always folderish, so the folder management features are available. We have to change this in future. But its not a bug.

Lets keep a reference to this problem at plone/plone.app.contenttypes#196 and close it here.

**Closed by jensens** 2015-10-05 13:48 UTC
