### ISSUE TITLE
Clicking "Cancel" while adding a new portlet gives a success messages "Portlet added"

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#727] opened 2015-07-19 12:53 UTC
Open portlets management and add an arbitrary new portlet to be added. Then click on "Cancel" within the configuration screen of the related portlet. A message "Portlet added" is being displayed.

**Comment by vangheem** [comment] 2015-07-19 13:22
Duplicate of https://github.com/plone/Products.CMFPlone/issues/728

**Closed by vangheem** 2015-07-19 13:22 UTC
