### ISSUE TITLE
Folderish content-types can not edited

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#318] opened 2014-12-05 13:20 UTC
The Plone 5.0a3 toolbar does not show the edit pencil for editing a folderish content-types.
Create a new Plone site.  There is no chance to edit for example the Users or News folder metadata.

**Comment by cewing** [comment] 2015-01-02 19:04
I cannot reproduce this problem.  Here's what I've tried so far:

1.  Create a brand-new site with the current Plone coredev buildout on the 5.0 branch
2.  Check both `Users` and `News`, both have the edit icon and can be edited in the expected fashion
3.  Create a new folder.  It has the edit icon and can be edited in the expected fashion
4.  Create a brand-new site with the Plone 5.0a3 versions.cfg used in the Plone 5.0a2 Unified installer
5.  Repeat #2 above
6.  Repeat #3 above

I am going to close this ticket.  

@zopyx Please feel free to re-open if you can provide better information on the 'steps to reproduce'

**Comment by cewing** [comment] 2015-01-02 19:04
closing as "cannot reproduce"

**Closed by cewing** 2015-01-02 19:04 UTC
Labels: bug
