### ISSUE TITLE
Remove Portal_css Portal_javascript

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#402] opened 2015-03-16 10:22 UTC
Its needed an upgrade step to remove portal_css portal_javascript on plone 5, also remove the PloneResourceRegistry

**Comment by bloodbare** [comment] 2015-04-13 10:37
As removing Plone Resource Registry would mean that jsregistry.xml import would not work we pospone this removal to plone 5.1

**Comment by pbauer** [comment] 2019-02-05 19:44
Duplicate of https://github.com/plone/Products.CMFPlone/issues/1742

**Closed by pbauer** 2019-02-05 19:44 UTC
