### ISSUE TITLE
Plone 4.3.11 -> 5.0.6 upgrade error

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1898] opened 2017-01-08 15:15 UTC
This buildout

https://github.com/EUDAT-DPMT/dpmt_buildout/tree/plone5

gives an migration error upgrading from 4.3.11 to 5.0.6 (also 5.1-latest)

````
Starting the migration from version: 4314
Ran upgrade step: Miscellaneous
Role / permission map imported.
Archetype tool imported.
Step languagetool has an invalid import handler
Upgrade aborted. Error:
Traceback (most recent call last):
  File "/Users/ajung/.buildout/eggs/Products.CMFPlone-5.0.6-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/Users/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/Users/ajung/.buildout/eggs/plone.app.upgrade-1.3.27-py2.7.egg/plone/app/upgrade/v50/alphas.py", line 34, in to50alpha3
    loadMigrationProfile(context, 'profile-plone.app.upgrade.v50:to50alpha3')
  File "/Users/ajung/.buildout/eggs/plone.app.upgrade-1.3.27-py2.7.egg/plone/app/upgrade/utils.py", line 134, in loadMigrationProfile
    context.runAllImportStepsFromProfile(profile, purge_old=False)
  File "/Users/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/tool.py", line 379, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
  File "/Users/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/tool.py", line 1414, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/Users/ajung/.buildout/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/tool.py", line 1226, in _doRunImportStep
    return handler(context)
  File "/Users/ajung/.buildout/eggs/Products.CMFPlone-5.0.6-py2.7.egg/Products/CMFPlone/resources/exportimport/bundles.py", line 28, in combine
    combine_bundles(site)
  File "/Users/ajung/.buildout/eggs/Products.CMFPlone-5.0.6-py2.7.egg/Products/CMFPlone/resources/browser/combine.py", line 109, in combine_bundles
    if PRODUCTION_RESOURCE_DIRECTORY not in container:
TypeError: argument of type 'NoneType' is not iterable
End of upgrade path, main migration has finished.
The upgrade path did NOT reach current version.
Migration has failed

```

**Comment by zopyx** [comment] 2017-01-08 15:30
```

> /Users/ajung/.buildout/eggs/Products.CMFPlone-5.0.6-py2.7.egg/Products/CMFPlone/resources/browser/combine.py(109)combine_bundles()
-> container = get_override_directory(context)
(Pdb) print context
<PloneSite at Plone>
(Pdb) get_override_directory(context)
```

**Comment by gforcada** [comment] 2017-01-09 10:19
Weirdly enough I saw that as well, but only once, I think the problem is that there is a filesystem folder referenced there and as soon as you create it you are good to go, but somehow we miss it when doing a release of CMFPlone(?) can you dig out which folder it is?

**Comment by zopyx** [comment] 2017-01-09 10:22
```
def get_override_directory(context):
    persistent_directory = queryUtility(IResourceDirectory, name="persistent")
    if persistent_directory is None:
        return
```


persistent_directory is None in my case.

**Comment by ale-rt** [comment] 2017-01-09 10:30
See also #1701

**Comment by zopyx** [comment] 2017-01-09 10:40
Adding 

profile-plone.resource:default

to the policy package profile (we have no theme package)

has no impact. Problem persists.

**Comment by mauritsvanrees** [comment] 2017-01-09 14:31
If it is the same as #1701, which looks like it, this was fixed in https://github.com/plone/plone.app.upgrade/pull/88, but it has not seen a release yet.

As workaround, you would need to install plone.resource via `portal_setup` before calling `@@plone-upgrade`.

**Comment by zopyx** [comment] 2017-01-09 14:49
Manual installation of plone.resource via portal_setup worked (import all steps).

However the theme is now broken, also @@skins-controlpanel gives a 404

![screenshot 2017-01-09 15 45 58](https://cloud.githubusercontent.com/assets/594239/21770362/3db19340-d683-11e6-897f-41d1b2e0c358.png)

**Closed** 2023-03-13 10:10 UTC
Labels: 99 tag: migration
