### ISSUE TITLE
Change javascript resources position to the bottom of page

### ISSUE THREAD

**Issue by rodfersou** [plone/Products.CMFPlone#1043] opened 2015-09-19 12:52 UTC
Webpages changed, and now there is a good practice to add all `javascript` files in the end of page.

One reason is that now script tags can go either into head tag or into body tag.
And for me, the main reason is to avoid the jquery ready funcion, it becomes useless if scripts tags are in the end of page because the `html` is already loaded in this point.

So, with this issue let's try to change the scripts position using the main page template or a diazo rule.

More resources to read:
- http://elegantcode.com/2010/03/30/your-javascript-goes-where/
- http://stackoverflow.com/questions/14547062/javascript-placed-at-the-end-of-the-document-so-the-pages-load-faster-true
- http://stackoverflow.com/questions/11786915/javascript-on-the-bottom-of-the-page

**Comment by rodfersou** [comment] 2015-09-19 12:53
@hvelarde @agnogueira @felipeduardo @vangheem @thet what do you think about it?

**Comment by vangheem** [comment] 2015-09-19 13:44
I like it but maybe it's just a diazo change? A theme decision

**Comment by rodfersou** [comment] 2015-09-19 13:46
@vangheem not sure, if it is a good practice, maybe we can change content first.. need to make some tests on it.. I saw some cases that this kind of change breaks some scripts..

**Comment by hvelarde** [comment] 2015-09-21 12:02
+1 on this; Goolge's [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/) is always complaining about this:

https://developers.google.com/speed/pagespeed/insights/?url=plone.org

**Comment by thet** [comment] 2015-10-06 10:07
I like it to, but once I've had some odd rendering issues when I tried to put all the JS to the bottom (via diazo). IIRC, Plone 4's "green bar" dropdowns were all expanded until the js was loaded - including other menus, which were hidden by Javascript? Cant remember exactly, but I had to switch back to JS in head.
We have to watch out for such regressions when experimenting with it.

**Comment by mauritsvanrees** [comment] 2015-10-06 11:00
Note that it can also interfere with inline javascript. On the http://www.zestsoftware.nl website, which is Plone 5, we had moved the javascript to the bottom and this gave a problem with an inline script that needed jQuery to be available. The inline script was in PloneFormGen, and in this case the solution was simply to remove the inline javascript because it was not necessary anymore or at least had no effect. See https://github.com/smcmahon/Products.PloneFormGen/commit/944a6ff5143e7b17b7de4a6fdb35cdfe1a5bc8d8

**Comment by davilima6** [comment] 2015-10-06 12:00
+1 for bottom, with proper testing.

jQuery, Modernizr and polyfills must be loaded at top to enable inline scripts that will try to run before full load (document.ready). And we also would have to load 3rd party JS in the end too.

Regarding @thet's concern about broken layout, I think the correct approach would be to improve our progressive enhancement story to make page rendering fine without JS. For instance, the menus could be handled with a combination of :hover, position, opacity, z-index and css transitions. Or with offleft positioning for better a11n. See:

* http://www.creativebloq.com/navigation/progressive-enhancement-menus-modernizr-10107112
* http://www.sitepoint.com/the-right-way-to-make-a-dropdown-menu/

Also might be worth having a look at:

* https://groups.drupal.org/node/8399

**Comment by davilima6** [comment] 2015-10-06 12:04
BTW I grepped around 50 ocurrences of document.write from Zope2, Products.ZCatalog, ExternalEditor, BTreeFolder but also from diazo, mockup, p.a.theming and Products.CMFPlone (used a lot in new resource registries to load scripts).

**Comment by frisi** [comment] 2015-10-07 10:34
most of the inline scripts should still work when moved the end of the body using diazo too.
something like this should do the trick for most of them:

```xml
  <!-- Copy script tags from Plone head to end of body -->
  <after css:theme-children="html body" css:content="html head script" />

  <!-- Move inline scripts in content to end of body -->
  <drop css:content="body script" />
  <after css:theme-children="html body" css:content="html body script" method="raw" />
```

**Comment by davisagli** [comment] 2022-08-24 21:49
@thet Is this something that was considered when updating Plone's js story for Plone 6 classic?

**Comment by jensens** [comment] 2023-03-13 11:41
Is this is still needed with async and deferred loading?

**Comment by thet** [comment] 2023-03-13 22:37
@davisagli @jensens right, with async and deferred this is actually not needed anymore.

Also Plone 6 classic now only loads only ~260kB minified by default, so the issue is not pressuring anymore anyways. Much of the size comes from jQuery and the Bootstrap JS being included directly in the default Plone bundle entry point file. And this bundle should not be loaded async or deferred so that other scripts can rely on the existance of jQuery (e.g. some plone.protect JS code‌ IIRC).

**Comment by thet** [comment] 2023-03-13 22:37
Closing as this is now obsolete.

**Closed by thet** 2023-03-13 22:37 UTC
Labels: 04 type: enhancement
