### ISSUE TITLE
Initial focus on title field and default action > save

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#2219] opened 2017-11-20 08:52 UTC
## Initial focus is not on title anymore

Until Plone 4, when creating or editing an object we have always the initial focus on the title field, whcih is not the case in Plone 5. This is anyoing and might also bad for accessibility.

## The default action is wrong since Plone 5

Until Plone 4 the default action on edit or add forms was set to submit, so that when pressing ENTER while focussing the title fileds where saving the object. Since Plone 5 that no longe the case and should be fixed.

The fix should be applying in Plone 5.0 and 5.1 series.

**Comment by MrTango** [comment] 2017-11-20 08:53
I thing #1549 is related to this general problem.

**Comment by pbauer** [comment] 2017-11-20 09:02
This is a duplicate of #779

**Comment by newbazz** [comment] 2017-12-03 17:01
I want to work on this issue.

**Comment by mrsaicharan1** [comment] 2018-02-27 15:55
I'd like to help fix this. Does this occur only when we are creating/editing a form? Could you point me to the file where this is possibly occurring?

**Comment by mrsaicharan1** [comment] 2018-02-27 15:57
Also, could you explain some of the places where this is occurring?

**Comment by mrsaicharan1** [comment] 2018-02-27 16:00
Also, could you explain some of the places where this is occurring?

**Comment by ArhantJain** [comment] 2018-03-09 20:56
Hii @MrTango,
I understand the issue you are depicting and now I want to work on it.
Because I have used Plone 4.3, I  experienced that accessibility while creating and editing the Events.

So, Please guide me the way of solving this issue and from where should I start?

**Comment by davisagli** [comment] 2022-08-24 22:44
Seems to be working correctly in Plone 6 classic

**Closed by davisagli** 2022-08-24 22:44 UTC
Labels: 02 type: regression, 99 tag: UX Editor, 41 lvl: easy
