### ISSUE TITLE
Contributors and Editors can no longer submit content in Plone 6

### ISSUE THREAD

**Issue by pbauer** [plone/Products.CMFPlone#3291] opened 2021-07-23 09:30 UTC
Since the view `content_status_modify` is protected by `cmf.ReviewPortalContent` Editors and Contributors can no longer submit content. 

To reproduce:

1. Login on Plone 5.2 (https://demo.plone.org) as a Editor. Create a page and submit it. Works.
2. Login on Plone 6 (https://6-classic.demo.plone.org) as a Editor. Create content and submit it. Fails with insufficient-privileges.

In https://github.com/plone/Products.CMFPlone/pull/3193 the old python-script was changed to a BrowserView but `permission="cmf.ReviewPortalContent"` prevents it to be called unless you are a Reviewer.

Changing the permission to `zope2.View` will fix the issue since the permissions to transitions are checked later anyway. The same is the case for the view `content_status_history`

**Comment by mauritsvanrees** [comment] 2021-07-26 19:05
That seems to make sense.

Since I was the one who turned the script into a browser view, I'll assign this to me so I don't lose track of it. But someone else should feel free to pick it up, as I don't have immediate plans to create a PR.
Original PR where I create the browser view, is https://github.com/plone/plone.app.content/pull/216/files

It would go good to add tests for this to catch regressions:

- Check that Contributor/Editor can submit content.
- Check that anonymous can **not** submit content.

**Comment by mauritsvanrees** [comment] 2022-09-29 20:39
Submitting for publication works now. I fixed it almost one year ago: https://github.com/plone/plone.app.content/pull/235

**Closed by mauritsvanrees** 2022-09-29 20:39 UTC
Labels: 01 type: bug, 02 type: regression, 12 prio: high
