### ISSUE TITLE
TinyMCE resources not found in Plone 5.1.4

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2608] opened 2018-10-31 07:16 UTC
See browser console in screenshot. 
This happens with a fresh Plone 5.1.4 when you edit the front-page.

![screenshot_20181031_081423](https://user-images.githubusercontent.com/594239/47771899-4a7b0d80-dce5-11e8-995f-6bc9d605d30d.png)

**Comment by hvelarde** [comment] 2018-10-31 12:47
this is the same as in #949, it was supposedly fixed in the past.

**Comment by petschki** [comment] 2019-03-02 20:24
this is not a bug in plone but a missing country specific translation in tinymce-builded (see all available tinymce language packages here https://github.com/artursmirnov/tinymce_builded/tree/master/js/tinymce/langs) ... the second error comes from the fallback trial (lng_LNG) in https://github.com/plone/mockup/blob/master/mockup/js/i18n.js#L21

**Comment by vincentfretin** [comment] 2020-06-27 15:54
The js code is completly wrong in https://github.com/plone/mockup/blob/ad2773a4dd810b673cdf285af798b7f1e7817da1/mockup/patterns/tinymce/pattern.js#L317
There is an issue about it there:
https://github.com/plone/mockup/issues/786
See:
```
"fr_FR".split('_')
(2) ["fr", "FR"]
"fr_FR".split('_') > 1
false
"fr_FR".split('_').length > 1
true
```

Currently on Plone 5.2.2 in French
It tries
http://0.0.0.0:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/fr.js
returns 404
then it tries
http://0.0.0.0:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/fr_FR.js
which is successful.

I think we should have a list of supported tinymce locales somewhere instead of doing a request, having a 404 and try another locale.

**Comment by ale-rt** [comment] 2022-08-24 08:37
I cannot reproduce this on:
- https://demo.plone.org/en/frontpage/edit
- https://6-classic.demo.plone.org/en/frontpage/edit

Probably fixed by some refactoring in the mockup package

**Closed by ale-rt** 2022-08-24 08:37 UTC
Labels: 02 type: regression
