### ISSUE TITLE
Importing content: AttributeError: uid_catalog

### ISSUE THREAD

**Issue by 3dogMcNeill** [plone/Products.CMFPlone#859] opened 2015-09-03 19:28 UTC
Tried to import folder with 7 news items (text only) to site root. Folder exported from v4.3.2.  

Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module OFS.ObjectManager, line 627, in manage_importObject
    Module OFS.ObjectManager, line 649, in _importObjectFromFile
    Module OFS.ObjectManager, line 359, in _setObject
    Module zope.event, line 31, in notify
    Module zope.component.event, line 24, in dispatch
    Module zope.component._api, line 136, in subscribers
    Module zope.component.registry, line 321, in subscribers
    Module zope.interface.adapter, line 585, in subscribers
    Module zope.component.event, line 32, in objectEventNotify
    Module zope.component._api, line 136, in subscribers
    Module zope.component.registry, line 321, in subscribers
    Module zope.interface.adapter, line 585, in subscribers
    Module OFS.subscribers, line 110, in dispatchObjectMovedEvent
    Module OFS.subscribers, line 143, in callManageAfterAdd
    Module Products.Archetypes.BaseFolder, line 95, in manage_afterAdd
    Module Products.Archetypes.BaseObject, line 159, in manage_afterAdd
    __traceback_info__: (<ATBTreeFolder at /Plone5/news>, <ATBTreeFolder at /Plone5/news>, <PloneSite at /Plone5>)
    Module Products.Archetypes.Referenceable, line 240, in manage_afterAdd
    Module Products.Archetypes.Referenceable, line 210, in _updateCatalog
    Module Products.CMFCore.utils, line 13, in check_getToolByName
    Module Products.CMFCore.utils, line 120, in getToolByName

AttributeError: uid_catalog

**Comment by pbauer** [comment] 2015-09-03 19:56
It seems you are trying to import archetypes-objects from Plone 4 into Plone 5. Exporting and re-importing zexp only works reliably when using the same Plone-Version. 
In this case you are missing the dependencies uid_catalog and (probably) reference_catalog. Try installing Products.ATContentTypes (the profile is called "Archetypes Content Types for Plone").

**Comment by 3dogMcNeill** [comment] 2015-09-03 20:33
aha! Thanks!



Christina

**Comment by vangheem** [comment] 2015-09-07 01:49
Closing this as it seems like it is not a bug.

**Closed by vangheem** 2015-09-07 01:49 UTC
