### ISSUE TITLE
"confirm action" Error message when adding group portlet

### ISSUE THREAD

**Issue by rileydog** [plone/Products.CMFPlone#1338] opened 2016-01-26 03:48 UTC
I get a strange message when I am trying to perform certain actions. the warning below I got when I was trying to add a group portal while in site setup/ groups and looking at particular group.  Also, This has happened on other actions that I can't remember. Once I click "confirm action" all works fine. I was logged in as admin or siteadmin.  see screen shot    (it was for plone 5 or 5.01

I posted this here: https://community.plone.org/t/i-get-this-strange-message-when-performing-certain-actions/1465  

In response, I got two replies
1) It happens when some code is trying to write to the database when it should not be. It's an overactive secure measure.  @vangheem 

2)  Dylan Jay posted the following in response: You will only get these errors once after site creation. Its a write on read error and normally is caused by initiazation code that runs only once and never again in a sites life time.  @djay 

![security message when trying to add group dashboard](https://cloud.githubusercontent.com/assets/1693063/12572045/0afec904-c39c-11e5-9197-be81683513af.png)

**Comment by djay** [comment] 2016-01-26 04:06
@rileydog great first bug report. I updated your title to make it more specific. Makes bugs hard to manage when they all say "got an strange error when I did something"

**Comment by vangheem** [comment] 2016-01-26 05:07
@rileydog sorry, I can't reproduce this. Can you give step by step instructions for how to reproduce this?

**Comment by rileydog** [comment] 2016-01-26 05:58
Thanks. Was a weak title 

___________________
Thanks, 

Wayne Glover 
(Sent from my iPhone)

**Comment by rileydog** [comment] 2016-01-26 06:31
Hi @vangheem ,  I reported elsewhere I was not able to reproduce this.  Might what @djay added above explain it?  I'm guessing.
   If this happens again (I've upgraded to 5.0.2 - don't know if that matters) I will take better attention and report.

**Comment by vangheem** [comment] 2016-02-02 03:13
Closing issue for now then. When you can reproduce, please reopen with details. Thanks, at least we have a record for it.

**Closed by vangheem** 2016-02-02 03:13 UTC
Labels: 01 type: bug
