### ISSUE TITLE
plone-legacy bundle forgets 3rd party resources after a restart

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#371] opened 2015-02-07 13:04 UTC
There seems to be a persistence issue with the plone-legacy bundle in Plone 5.0a3.

I encountered the following behavior with the Plone 5 buildout used in this add-on:

https://github.com/xml-director/xmldirector.plonecore

After creating a new Plone site and adding the XML Director add-on I can see the related resources in the plone-legacy bundle (see screenshot). After restarting Plone and reloading the same view: all XML director related resources have gone.

![screenshot 2015-02-07 13 55 49](https://cloud.githubusercontent.com/assets/594239/6092173/4251b36a-aed2-11e4-9244-e49671b82d2d.png)
![screenshot 2015-02-07 14 01 18](https://cloud.githubusercontent.com/assets/594239/6092174/42538424-aed2-11e4-8172-149780e40583.png)

**Comment by vangheem** [comment] 2015-02-08 18:12
When I try installing XML Director with the Plone 5 core buildout, I get an error. The error seems to be from cooking the legacy js--looking.

**Comment by vangheem** [comment] 2015-02-08 19:37
I can not reproduce the issue you describe. I have however, fix the cooking issue: https://github.com/plone/Products.CMFPlone/commit/03dabac6f4569c2d682bdeaeb670326d770219d7

Are you using the core dev buildout?

**Comment by zopyx** [comment] 2015-02-08 19:40
I am not getting an error using the provided 5.0 cfg file.



2015-02-08 20:37 GMT+01:00 Nathan Van Gheem <notifications@github.com>:

**Comment by vangheem** [comment] 2015-02-08 19:48
hhmm, right. We haven't had a release in a long time and there has been enough changes since then.

I'm not sure what to recommend here besides trying with coredev buildout; however, that's not realistic for testing buildout purposes(or maybe it could be).

**Comment by vangheem** [comment] 2015-02-08 23:18
Since I can not reproduce this in master, I'm going to close this issue even though I can not identify what commit would have fixed the behavior you're sing. Please re-open if this problem still persists after testing on coredev buildout or after the next release. Thanks.

**Closed by vangheem** 2015-02-08 23:18 UTC
