### ISSUE TITLE
CSS issue/usability  in "actions" control panel

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2480] opened 2018-07-31 05:40 UTC
![screenshot-localhost-10081-2018 07 31-07-34-30](https://user-images.githubusercontent.com/594239/43439672-7f2611c2-9494-11e8-9b7c-7f1a517aa285.png)

The width of the "Hide" and "Show" button are different but they should have the same width (looks ugly and unprofessional.

This control panel also has usability flaw because you can not detect easily which actions are visible or invisible. The existence of "Hide" tells you that it is show (you have to negate the sematics of the button)...same for "Show"...a toogle switch (similar to https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_switch) would be more intuitive. Or make shown actions green or bold...at least something to distinguish hidden from shown actions.

**Comment by ashutoshsenger** [comment] 2018-08-01 18:03
hey, my self ashutosh  senger and i want to fix this bug.

**Comment by Rupeshiya** [comment] 2018-08-30 13:09
I would like to fix this issue .Can I fix @zopyx .

**Comment by yshgpta** [comment] 2018-08-31 14:05
Hey there, myself Yash Gupta and I want to work on this issue and it seems easy fix for me to work through....@zopyx

**Comment by zopyx** [comment] 2018-08-31 14:29
Guys, stop misusing the Plone bugtracker for finding a mentor. This attitude is highly annoying,

**Comment by shashwatmishra76** [comment] 2018-09-13 06:57
Hello! I am new to Plone.Can I be assigned to this issue?

**Comment by djay** [comment] 2018-09-16 15:43
@shashwatmishra76 just fix it and submit a PR. There is no assignment.

**Comment by uwaiszaki** [comment] 2018-12-09 17:02
hey , Can i work on this issue if no one is working on it

**Comment by tkimnguyen** [comment] 2018-12-09 20:21
@uwaiszaki @Rupeshiya @yshgpta @shashwatmishra76  if you want to fix it or any other Plone issue, just go ahead and do so and make a pull request. Before we can merge a pull request in the "plone" GitHub organization you will have to have signed a contributor agreement. See https://plone.org/foundation/contributors-agreement and https://plone.org/get-started. For further guidance on how to contribute to Plone, please make an introductory post in our forum, https://community.plone.org/  and we can discuss there.

**Comment by uwaiszaki** [comment] 2018-12-10 17:01
Can you tell me where to find the respective files?

**Comment by uwaiszaki** [comment] 2018-12-11 15:53
Barceloneta Theme is not editable. So how to edit the css file ?

**Comment by virendrarajpurohit** [comment] 2019-02-01 18:30
Hi! I am Working On this issue.

**Comment by uwaiszaki** [comment] 2019-02-01 20:34
@virendrarajpurohit  I have already solved this issue and submitted a pr.

**Comment by virendrarajpurohit** [comment] 2019-02-02 18:54
@uwaiszaki can't see in which pr you have made the changes because it's not in the pr list.also this is not updated in plone.

**Comment by uwaiszaki** [comment] 2019-02-02 20:34
@virendrarajpurohit . Pr is on plonetheme.barceloneta repo. [https://github.com/plone/plonetheme.barceloneta/pull/171](url)

**Comment by tmassman** [comment] 2019-03-07 10:37
@uwaiszaki The PR brings more problems than it solves and was merged too quickly. Instead of setting a fixed width it would be better to have a min width. The problem is there will always be languages where the length of the button text differs.

Also, we now have UI bugs on other places.
<img width="140" alt="screenshot 2019-03-07 at 11 36 29" src="https://user-images.githubusercontent.com/1116199/53950826-5a5c9100-40cd-11e9-8c7d-7dd04a1a93b1.png">

**Comment by pbauer** [comment] 2019-07-19 08:40
@uwaiszaki: Can you please revert your changes?

**Comment by vincentfretin** [comment] 2019-10-13 15:00
The current style in Plone 5.2 is far more worse to what we had in the original issue. :)
This is what it looks like in French:
![Capture d’écran de 2019-10-13 16-59-03](https://user-images.githubusercontent.com/112249/66717566-d09b4180-edda-11e9-9498-f6d20d41248f.png)

**Comment by rakshitgondwal** [comment] 2022-08-29 04:26
Is this issue still open?

**Comment by jensens** [comment] 2023-03-12 23:09
This was all fixed

**Closed by jensens** 2023-03-12 23:09 UTC
Labels: 01 type: bug, 99 tag: UX Site Admin, 14 prio: low, 21 status: confirmed, 41 lvl: easy
