### ISSUE TITLE
Impossible to insert an internal image (Plone 5.0.3-pending) for non-English site

### ISSUE THREAD

**Issue by serge73** [plone/Products.CMFPlone#1450] opened 2016-03-08 18:51 UTC
Plone 5.0.3 after upgrade 5.0.2:

Impossible to insert an internal image when the document is edited.
Can find, but can't insert.

**Comment by serge73** [comment] 2016-03-14 20:07
solution: downgrade plone.app.content to version 3.0.17

Add new issue: https://github.com/plone/plone.app.content/issues/77#issue-140782426

**Comment by serge73** [comment] 2016-03-22 19:22
The problem appears when using Russian, Polish, African and probably any other non-English

**Comment by davilima6** [comment] 2016-04-06 03:05
Duplicate of plone/plone.app.content#77

**Closed by davilima6** 2016-04-06 03:05 UTC
Labels: 01 type: bug
