### ISSUE TITLE
After upgrading from Plone 5.0RC1 to RC3 the portal-tabs in portal-globalnav end with /view

### ISSUE THREAD

**Issue by jladage** [plone/Products.CMFPlone#1079] opened 2015-09-24 21:21 UTC

**Comment by vangheem** [comment] 2015-09-25 02:22
I can't reproduce this. Can you go to Site Setup -> Configuration registry -> search "types_use_view_action_in_listings" and see what the value there is?

**Comment by jladage** [comment] 2015-09-25 05:15
That's exactly the issue. it was set to "Folder", "FormFolder", but it's not updated with the migration.
I had pfg installed in this site.

**Comment by pbauer** [comment] 2015-09-25 07:02
This is a duplicate of https://github.com/plone/Products.CMFPlone/issues/1073 which is fixed in https://github.com/plone/plone.app.upgrade/commit/d4d7fe0805fd5f81e2259a3202ca906741b721b4

**Closed by pbauer** 2015-09-25 07:02 UTC
