### ISSUE TITLE
plone.app.content circular dependency on Products.CMFPlone

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#305] opened 2014-11-18 14:07 UTC
plone.app.content depends on Products.CMFPlone and vice versa. This must be solved.

**Comment by jensens** [comment] 2015-03-18 12:43
so we're depending on a whole bunch of plone.app.*:

        'plone.app.content',
        'plone.app.contentlisting',
        'plone.app.contentmenu >= 1.1.6dev-r22380',
        'plone.app.contentrules',
        'plone.app.contenttypes',
        'plone.app.controlpanel',
        'plone.app.customerize',
        'plone.app.dexterity',
        'plone.app.discussion',
        'plone.app.folder',
        'plone.app.form',
        'plone.app.i18n',
        'plone.app.jquerytools',
        'plone.app.layout >=1.1.7dev-r23744',
        'plone.app.linkintegrity >=1.0.3',
        'plone.app.locales',
        'plone.app.portlets',
        'plone.app.redirector',
        'plone.app.registry',
        'plone.app.theming',
        'plone.app.users',
        'plone.app.uuid',
        'plone.app.viewletmanager',
        'plone.app.vocabularies',
        'plone.app.widgets',
        'plone.app.workflow',

**Comment by gforcada** [comment] 2015-03-18 13:11
But that's fine, isn't it? The problem is if any of those packages depend on CMFPlone...

**Comment by gforcada** [comment] 2015-03-18 13:12
Although, just like with p.a.controlpanel and p.a.search, some of them could be merged into CMFPlone.

**Comment by jensens** [comment] 2015-03-18 14:02
Its fine, its just because of what @thet wrote

**Closed** 2021-12-07 23:09 UTC
Labels: 99 tag: dependencies
