### ISSUE TITLE
Javascript package problem on Jenkins 5.1 due to grunt version

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFPlone#1623] opened 2016-06-06 06:20 UTC
The Plone 5.1 JavaScript Jenkins job is broken since this weekend. See http://jenkins.plone.org/job/plone-5.1-js/4/
The previous job run was on 28 April, so this is not regularly run. Jenkins says it was started by this push to mockup, but that seems totally innocent: https://github.com/plone/mockup/commit/cbfd3fdb41027ecc6264ae1368a8a26dcb743697
I tried a manual rebuild, but it gives the same error:

```
npm ERR! peerinvalid The package grunt does not satisfy its siblings'
  peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-karma@1.0.0 wants grunt@>=0.4.x
npm ERR! peerinvalid Peer grunt-sed@0.1.1 wants grunt@~0.4
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
```

**Comment by l34marr** [comment] 2016-08-17 07:12
I run into the same error message when following the instruction at http://mockup-training.readthedocs.io/ Somehow it seems to be fixed by the hint at http://github.com/gruntjs/grunt/issues/1488 Specifically I change the mockup/package.json file with this: `"grunt": ">=0.4.5 <1.0.0"`

HTH

**Comment by gforcada** [comment] 2016-08-17 07:53
@l34marr would you mind providing a pull request to mockup with this fix?

**Comment by l34marr** [comment] 2016-08-18 09:45
@gforcada Based on http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released#peer-dependencies I guess the right way is to fix the Grunt plugin, which in our case is `grunt-sed`. The update is at https://github.com/jharding/grunt-sed/pull/16 but not yet be merged and released. My JavaScript knowledge is limited, but I don't think it's a good idea to fix mockup/package.json file this way. Hints are appreciated.

**Comment by gforcada** [comment] 2016-08-18 11:41
@l34marr no problem at all! as I saw you providing some hints on the root cause I thought that it could  be solved on our side, but if there is a PR already fixing it upstream, then let's push for that PR and update to the version that contains it once is released.

Thanks for finding the issue and pull request!

**Comment by gforcada** [comment] 2016-08-26 22:03
I have a solution at https://github.com/plone/mockup/pull/702 as npm allows to use github URLs as versions, we can fork a fix for it and use that :+1:

**Comment by gforcada** [comment] 2016-11-27 20:39
That was merged long ago.

**Closed by gforcada** 2016-11-27 20:39 UTC
Labels: 01 type: bug, 31 needs: help
