### ISSUE TITLE
Tinymce Image Upload: broken image

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#1149] opened 2015-10-09 09:30 UTC
If you upload an image with tinymce there is a broken image:

From debugger:

```
7plone-logged-in-compiled.min.js:1 patterns.Patternslib Base: This pattern without a name attribute will not be registered!
2plone-logged-in-compiled.min.js:50 Usage of the mockup-patterns-base pattern is deprecated and it will eventually be removed.Instead, use pat-base and explicitly set parser to 'mockup' when calling extend.
http://localhost:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/en.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/Plone/++plone++static/components/tinymce-builded/js/tinymce/langs/en_EN.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/Plone/news/@@images/image/thumb Failed to load resource: the server responded with a status of 404 (Not Found)
```
![tinymce_image_upload](https://cloud.githubusercontent.com/assets/918640/10390476/2bdd4ed4-6e79-11e5-93fb-61c3581d3307.png)

**Comment by davilima6** [comment] 2016-07-05 12:53
Duplicate of plone/plone.app.content#77.

**Closed by davilima6** 2016-07-05 12:53 UTC
Labels: 01 type: bug
