### ISSUE TITLE
Add plone.com links to front-page boilerplate text

### ISSUE THREAD

**Issue by esteele** [plone/Products.CMFPlone#575] opened 2015-05-29 22:17 UTC
Under the "Tell us how you use it" section, there are three links that should get pointed to the relevant pages on plone.com

**Comment by vangheem** [comment] 2015-07-13 06:09
Closing as duplicate of https://github.com/plone/Products.CMFPlone/issues/575

**Closed by vangheem** 2015-07-13 06:09 UTC
Labels: Sprint
