### ISSUE TITLE
Drag & drop folder content reordering fails

### ISSUE THREAD

**Issue by sgmentzer** [plone/Products.CMFPlone#2206] opened 2017-11-06 07:03 UTC
On a fresh install of 5.1rc1, rearranging items in a folder via drag & drop fails. This error appears in the browser console upon dropping.

    TypeError: window[b.options.drop] is not a function  plone-logged-in-compiled.min.js:25:3544
        init/< http://127.0.0.1:8080/rctc/++plone++static/++unique++2017-10-01%2017%3A21%3A25/plone-logged-in-compiled.min.js:25:3544
        dispatch http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:8497
        b.dispatch http://127.0.0.1:8080/rctc/++plone++static/++unique++2017-10-01%2017%3A21%3A25/plone-compiled.min.js:4:17127
        hijack/< http://127.0.0.1:8080/rctc/++plone++static/++unique++2017-10-01%2017%3A21%3A25/plone-compiled.min.js:4:15621
        each http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:2:2973
        each http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:2:833
        hijack http://127.0.0.1:8080/rctc/++plone++static/++unique++2017-10-01%2017%3A21%3A25/plone-compiled.min.js:4:15516
        handler http://127.0.0.1:8080/rctc/++plone++static/++unique++2017-10-01%2017%3A21%3A25/plone-compiled.min.js:4:15061
        dispatch http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:8497
        b.dispatch http://127.0.0.1:8080/rctc/++plone++static/++unique++2017-10-01%2017%3A21%3A25/plone-compiled.min.js:4:17127
        add/r.handle http://127.0.0.1:8080/rctc/++plone++static/components/jquery/dist/jquery.min.js:4:5235

**Versions:**

* Plone 5.1rc1 (5108)
* CMF 2.2.12
* Zope 2.13.26
* Python 2.7.9 (default, Oct 18 2017, 02:13:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
* PIL 4.2.1 (Pillow)

**Comment by agitator** [comment] 2017-11-06 07:12
had the same problem, looks like it's fixed in master

@thet ?

**Comment by petschki** [comment] 2017-11-27 10:10
same here ...

**Comment by thet** [comment] 2017-11-27 10:15
Duplicate of https://github.com/plone/mockup/issues/808 and fixed with https://github.com/plone/mockup/pull/809
Should land in 5.1rc2. Test it with: http://dist.plone.org/release/5.1rc2-pending/

**Closed by thet** 2017-11-27 10:15 UTC
Labels: 01 type: bug

**Comment by petschki** [comment] 2017-11-27 10:59
@thet thank you! in a fresh 5.1rc2 installation it works. My 5.1rc1 installation refuses to work, even when resource registry is running in debug mode and recompiling plone-logged-in bundle ... also all the tinymce icons are gone ... can you give me a hint how to fix this in the resource registry? is there a missing upgrade step?
