### ISSUE TITLE
Full folder view gives @@uuid error

### ISSUE THREAD

**Issue by espenmn** [plone/Products.CMFPlone#1211] opened 2015-10-26 16:39 UTC
1) add a Plone 5 site,
2) Set the view (on root) to all content
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Products.Five.browser.metaconfigure, line 485, in __call__
    Module Products.Five.browser.pagetemplatefile, line 125, in __call__
    Module Products.Five.browser.pagetemplatefile, line 59, in __call__
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Module five.pt.engine, line 93, in __call__
    Module z3c.pt.pagetemplate, line 163, in render
    Module chameleon.zpt.template, line 258, in render
    Module chameleon.template, line 191, in render
    Module chameleon.template, line 171, in render
    Module c2a8ce17b741c01c7b9f8addaec9a01c.py, line 278, in render
    Module 3e26d41978c3a820f05073a4fc3a0560.py, line 1223, in render_master
    Module 3e26d41978c3a820f05073a4fc3a0560.py, line 420, in render_content
    Module c2a8ce17b741c01c7b9f8addaec9a01c.py, line 266, in __fill_content_core
    Module c2a8ce17b741c01c7b9f8addaec9a01c.py, line 92, in render_content_core
    Module five.pt.expressions, line 154, in __call__
    Module five.pt.expressions, line 123, in traverse
    Module OFS.Traversable, line 300, in unrestrictedTraverse
    __traceback_info__: ([], '@@uuid')

AttributeError: @@uuid

 - Expression: "context/@@uuid"
 - Filename:   ... gg/plone/app/contenttypes/browser/templates/full_view.pt
 - Location:   (line 12: col 30)
 - Source:     tal:define="uuid context/@@uuid">
                                ^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x10c4244c>
               views: <ViewMapper - at 0x10f24c6c>
               modules: <instance - at 0xa086fcc>
               args: <tuple - at 0xb758702cL>
               here: <ImplicitAcquisitionWrapper xxxxx at 0x10afc02c>
               user: <ImplicitAcquisitionWrapper - at 0x10b1d07c>
               nothing: <NoneType - at 0x818e5c0>
               container: <ImplicitAcquisitionWrapper xxxxx at 0x10afc02c>
               request: <instance - at 0x106b850c>
               wrapped_repeat: <SafeMapping - at 0x1061b84c>
               traverse_subpath: <list - at 0x10628a4c>
               default: <object - at 0xb75a67f8L>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper xxxxx at 0x10afc02c>
               view: <SimpleViewClass from /home/espen/instance8095/Plone5/buildout-cache/eggs/plone.app.contenttypes-1.2.4-py2.7.egg/plone/app/contenttypes/browser/templates/full_view.pt full_view at 0xfb5e6cc>
               translate: <function translate at 0x107b133c>
               root: <ImplicitAcquisitionWrapper Zope at 0x10b3661c>
               options: {...} (0)
               target_language: <NoneType - at 0x818e5c0>

**Comment by pbauer** [comment] 2015-10-26 18:55
Duplicate of #1109. Workaound if you broke your site: go to ``/select_default_view`` and select a different view that ``All content``.

**Closed by pbauer** 2015-10-26 18:55 UTC

**Comment by thet** [comment] 2015-10-26 19:22
It's fixed in plone.app.contenttypes 1.2.5, which is unreleased at the moment. next plone release should include the fix.
