### ISSUE TITLE
Listing in folder_contents

### ISSUE THREAD

**Issue by svx** [plone/Products.CMFPlone#2249] opened 2017-12-21 08:02 UTC
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

Background

In Plone 4 we have on the bottom of the listing “Show all content”

It seems that this is gone in Plone 5.x.

You can find more info on [community.plone.org](https://community.plone.org/t/listinig-in-folder-contents/5432/2).

### What I did:

* Plone 5 with the official plone.docker build
* http://demo.plone.de/en

If you add more than 15 content items there is no "show all items"

* Plone 4 -> there you have "show all items"

### What I expect to happen:

That I have this also in Plone 5

### What actually happened:

No "show all items"

**Comment by vincentfretin** [comment] 2020-07-03 10:55
duplicate of https://github.com/plone/Products.CMFPlone/issues/735

**Closed by vincentfretin** 2020-07-03 10:55 UTC
Labels: 02 type: regression
