### ISSUE TITLE
Upload image in portlet on site root does not work

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#3637] opened 2022-09-05 12:25 UTC
### What I did:

Upload an image in a portlet (on the site root, did not test at other locations).

### What I expect to happen:
Upload stores new image in site root.

### What actually happened:

Upload fails.

### What version of Plone/ Addons I am using:

Vanilla Plone 6.0.0b2

**Comment by mauritsvanrees** [comment] 2022-09-07 11:58
I get a 404 NotFound on `http://localhost:8080/Plone/++contextportlets++plone.leftcolumn/@@fileUpload`.
Trying to browse to home and upload it there has no effect: same error because you cannot really select home.
When I select the news folder, I can upload the new image there.

Not sure what the best fix would be:

- Change some code (mockup?) to strip away url parts with `++contextportlets++` in them.
- Register `@@fileUpload` to work in this portlet context as well, picking the parent folder as target.

**Comment by ale-rt** [comment] 2022-09-07 12:10
This is a duplicate of #2283

**Closed** 2022-09-07 19:35 UTC
Labels: 01 type: bug, 13 prio: normal, 21 status: confirmed
