### ISSUE TITLE
folder_content JS broken, does not update context

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#2452] opened 2018-06-19 14:06 UTC
## Bug

The folder_content view does not update the context in the toolbar and in the breadcrumbs.

I can see the following JS error in the console:

`TypeError: t.$el.parent.replaceWith is not a function`

### What I did:

change folder in forder_content

### What I expect to happen:

the toolbar and breadcrumb reflects the chnages

### What actually happened:

The toolbar and breadcrumb still has the old context and therefor did not update the add menu correctly.

### What version of Plone/ Addons I am using:

Plone5.1-latest:

Plone 5.1.2.1 (5112)

**Comment by MrTango** [comment] 2018-06-19 14:07
I could reproduce this in two separate installations.

**Comment by tomgross** [comment] 2018-06-19 14:55
This is a duplicate of #2395

**Closed by tomgross** 2018-06-19 14:55 UTC
Labels: 01 type: bug, 12 prio: high
