### ISSUE TITLE
Selection of Time Zone in user preferences does not stick

### ISSUE THREAD

**Issue by rileydog** [plone/Products.CMFPlone#1290] opened 2015-12-18 00:30 UTC
I am having trouble with the timezone setup.

1) under personal preferences, when I select a timezone and press save, it reverts to "none selected.

This issue discussed here:  https://community.plone.org/t/is-setting-the-time-zone-supposed-to-change-the-time-recorded-on-the-site/1303

I confirmed this bug with @cewing

**Comment by jdpye** [comment] 2017-01-31 15:37
Bumping this because it looks orphaned and has no assignees. Bug still active in Plone 5.0.6. When will this be addressed?

**Comment by CrispySteak** [comment] 2017-07-19 18:31
I can confirm that this bug is still in Plone 5.0.7. Doesn't look like any progress has been made.

**Comment by eric-jahn** [comment] 2018-05-25 17:50
In 5.1.2 the settings stick in the settings page, but my content still shows UTC times.  I set it to Los Angeles.

**Comment by ale-rt** [comment] 2022-08-24 20:41
I am working on this.
The problem is that this adapter wants to set a property that is not in the memberdata properties and this fails silently:
https://github.com/plone/plone.app.users/blob/575fe2bb60201f795387f322dd5318b86efd62c0/plone/app/users/browser/account.py#L71-L78
This appears to be a valid fix:
```
ale@avo:~/Code/plone/projects/coredev/6.0/src/plone.app.users$ cat plone/app/users/profiles/default/memberdata_properties.xml
<?xml version="1.0"?>
<object name="portal_memberdata" meta_type="PlonePAS MemberData Tool">
 <property name="timezone" type="string"></property>
</object>
```

I will work on a patch.

**Comment by ale-rt** [comment] 2022-08-25 08:23
A quick fix for this is to go to the portal_menberdata tool (e.g. https://demo.plone.org/portal_memberdata/manage_propertiesForm) and add the timezone property (see the form at the bottom of the page).
![image](https://user-images.githubusercontent.com/1300763/186614160-539754f6-741d-484e-973e-750fea55363f.png)

**Closed** 2022-08-25 15:26 UTC
Labels: 01 type: bug, 31 needs: help, 12 prio: high, 21 status: confirmed, 42 lvl: moderate, 99 tag: Plone 6.0, 99 tag: Plone 5.2

**Comment by ale-rt** [comment] 2022-08-25 15:36
I am reopening it because on Plone 5.2. this is still an issue
