### ISSUE TITLE
Missing link to @@dashboard on the toolbar

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#1805] opened 2016-10-22 21:56 UTC
I noticed that the toolbar does not have a link to the user personal dashboard (``/@@dashboard``). It's been a while since Plone 5 was out and nobody noticed so far, is that something we want to keep as is, or add it back again?

Opinions?!

**Comment by davisagli** [comment] 2016-10-23 02:54
Duplicate of #1132. #1262 re-adds it but needs to be updated and also an upgrade step.

**Closed by davisagli** 2016-10-23 02:54 UTC
