### ISSUE TITLE
Personal preferences: only one time zone?

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#903] opened 2015-09-09 15:23 UTC
Is it right that only one African timezone popups in the personal preferences?
![screenshot 2015-09-09 17 22 15](https://cloud.githubusercontent.com/assets/594239/9766065/6c3892d2-5717-11e5-8c03-1bfcf07f27fe.png)

**Comment by zopyx** [comment] 2015-09-09 15:29
I see...this is the default timezone chosen during the creation of the Plone site.

Question: what would be a reasonable default for the TZ within @@add-site? UTC?

**Comment by hvelarde** [comment] 2015-09-09 16:50
maybe the time zone selected in the OS

**Comment by jaroel** [comment] 2015-09-09 17:04
It strikes me as odd that there's only one option; I expected all timezones, with 'None' (Site setting) as the default.

The default timezone should probably be handled in #847

**Comment by thet** [comment] 2015-09-09 19:52
@@add-site chooses a timezone based on some browser request hints, which works OK for me (it's choosing Europe/Berlin instead of Europe/Vienna, but that's OK). This is handled here, using the jstz ( http://pellepim.bitbucket.org/jstz/ ) library: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/browser/templates/plone-addsite.pt#L26

**Comment by thet** [comment] 2015-09-09 20:13
aha, @@add-site choose the first entry in the timezone list, the cause will most likely be issue #847 .

**Comment by pbauer** [comment] 2015-09-19 10:37
Duplicate of #847

**Closed by pbauer** 2015-09-19 10:37 UTC
Labels: Bug
