### ISSUE TITLE
Inconsistent visual representation of links and behaviour for a:hover

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#2302] opened 2018-02-11 08:03 UTC
See screenshots made with Plone 5.1RC2

* The links in the portlet slots are not underlined vs. underlined links in the main slot

* a:hover on a link in the main slot will remove the underline from the document icon and leave it with the link text. a:hover on a link in a portlet will a an underline....

...that does not feel consistent....
![s1](https://user-images.githubusercontent.com/594239/36071177-7a281a9a-0f0a-11e8-9322-4d281224bf5b.png)

<img width="524" alt="bildschirmfoto 2018-02-11 um 09 00 19" src="https://user-images.githubusercontent.com/594239/36071179-7e7a04fa-0f0a-11e8-81e4-36e30b879bb3.png">

**Comment by mrsaicharan1** [comment] 2018-02-12 13:01
What is the expected behavior when we hover the mouse over the Document 1,Document 2 heading and the like? I would like to look into this issue.

**Comment by zopyx** [comment] 2018-02-12 13:04
The expectation is a consistent behaviour across all links.

**Comment by mrsaicharan1** [comment] 2018-02-12 13:12
Can you point me to the exact file as to where this is occurring ?

**Comment by zopyx** [comment] 2018-02-12 13:19
https://www.plone-demo.info/documents

**Comment by mrsaicharan1** [comment] 2018-02-12 18:20
@zopyx So would it be consistent if the words(for example Document1) changed from blue to red?

**Comment by zopyx** [comment] 2018-02-12 18:29
Your question does not make sense to me. I don't know what the intention of the Plone developers here is and how things are supposed to be. I don't care if something is green or blue...but it should not be green in one case or blue in the other case. The behaviour must be consistent. It is obvious that the current behaviour is inconsistent.

**Comment by iconoyuri** [comment] 2022-04-16 07:54
Hello everyone 
I want to fix this issue. It may be quite easy to do 
Can anyone show me the folder which may contain the different stylesheets which are applying to that page?

**Comment by iconoyuri** [comment] 2022-04-16 07:55
I don't know if it is necessary to precise it, but I'm applying as a GSoC contributor for Plone

**Comment by wesleybl** [comment] 2022-04-18 13:41
@iconoyuri the first thing for you to contribute to Plone is to sign and submit the Contributor’s Agreement. To see:

https://plone.org/foundation/contributors-agreement

**Comment by iconoyuri** [comment] 2022-04-18 20:31
Thank you for the information.

Le lundi 18 avril 2022, Wesley Barroso Lopes ***@***.***> a
écrit :

**Comment by jensens** [comment] 2023-03-12 23:44
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Closed by jensens** 2023-03-12 23:44 UTC
Labels: 01 type: bug, 31 needs: help, 14 prio: low, 41 lvl: easy
