### ISSUE TITLE
Collection criteria is lost when selecting more than one type

### ISSUE THREAD

**Issue by fulv** [plone/Products.CMFPlone#1344] opened 2016-01-28 04:22 UTC
Plone 5.0.2

1. Create a collection.
2. Under _Search terms_, choose **Type** and then pick two or more types from the select field.
3. Save
4. Notice _No results were found_
5. Go back to Edit

Result:  the types selected in step 2 are gone.

(If you select only one type in step 2, it works.)

**Comment by vangheem** [comment] 2016-02-02 03:11
duplicate of https://github.com/plone/Products.CMFPlone/issues/1328

**Closed by vangheem** 2016-02-02 03:11 UTC
Labels: 02 type: regression
