### ISSUE TITLE
New toolbar looks very nice but might be not efficient in some cases

### ISSUE THREAD

**Issue by Martronic-SA** [plone/Products.CMFPlone#663] opened 2015-07-02 14:12 UTC
I like the 100% height submenu but sometimes it's not the most efficient (if the aim is to have less mouse displacement).

![plonetoolbar](https://cloud.githubusercontent.com/assets/6492010/8478909/a417d600-20d4-11e5-831f-80d5b8cdb868.jpg)

Maybe it would be be better to have a submenu vertical position attached to the clicked toolbar menu.

**Comment by vangheem** [comment] 2015-07-02 14:22
Thanks for the feedback!

We're going to take a hard look at the toolbar at the anniversary sprint.

All UIs have compromises and we're trying to find the best toolbar for Plone. Things we put into consideration:

- ease of use
- accessibility
- compatibility with themes
- mobile support
- visuals
- etc

With user testing I've done so far and my personal opinion, I think the vertical toolbar is the best option at this point. It still needs tweaking though(especially button order).

**Comment by vangheem** [comment] 2015-07-13 04:41
Closing as duplicate of https://github.com/plone/Products.CMFPlone/issues/482 and https://github.com/plone/Products.CMFPlone/issues/529

**Closed by vangheem** 2015-07-13 04:41 UTC
Labels: Sprint
