### ISSUE TITLE
Linkintegrity in Plone 5 

### ISSUE THREAD

**Issue by bloodbare** [plone/Products.CMFPlone#698] opened 2015-07-16 17:35 UTC
1. Remove the dependeny of the linkintegrity-feature (plone.app.linkintegrity) to Products.Archetypes (it stores the relevant info in the reference_catalog). Store the linkintegrity-info instead in the relation_catalog (ICatalog of zc.relation). 
2. Change the implementation of linkintegrity: No longer intercept the request that deletes an object and only continue if there are no issues or the user choses to delete anyway (see https://github.com/plone/plone.app.linkintegrity/blob/2ded29afc83b28f0e91d05725a1b15df4f9c344c/plone/app/linkintegrity/NOTES.txt). Instead adapt delete_confirmation to do the check and display the warnings. 
3. We also need a simple way for developers who chose to use other deletion-methods (api.content.delete) to first check for linkitengrity-breaches.

**Comment by pbauer** [comment] 2015-07-22 17:37
Things done at anniversary-sprint 2015 and afterwards (by @bloodbare, @pbauer and @vangheem):

- Drop the Archetypes-dependency by switching to use zc.relation instead of reference_catalog (Products.Archetypes).
- No longer intercept the request on manage_deleteObjects. Instead only inject a warning in delete_confirmation. This means that deleting with other methods (like manage_deleteObjects, plone.api.content.delete, ttw using the ZMI) no longer warns about linkintegrity-breaches.
- LinkIntegrityNotificationException inno longer thrown anywhere

Todos:

- [ ] ``test_file_reference_linkintegrity_page_is_shown`` is throwing ``HTTPError: HTTP Error 500: Internal Server Error`` (only for Dexterity!)
- [ ] There may be a permission-problem: When deleting the linked obj the relation is deleted by ``z3c.relationfield.event.breakRelations``. That also fires ``ObjectModifiedEvent`` on the linked obj even though the user might not have the permission to edit that obj. Thus ``plone.app.versioningbehavior.subscribers.create_version_on_save`` is triggered and results in ``Unauthorized: You are not allowed to access 'save' in this context``
- [ ] Optional: Maybe add a parameter to ``plone.api.content.delete`` that checks for linkintegrity-breaches before deleting? What should it do if it happens?
- [ ] Upgrade docs

**Comment by davisagli** [comment] 2015-07-22 17:48
> This means that deleting with other methods (like manage_deleteObjects, plone.api.content.delete, ttw using the ZMI) no longer warns about linkintegrity-breaches.

IMO this makes the feature much less useful, because it no longer guarantees that relations won't be broken accidentally. Are we at least checking for breaches when items are deleted from folder contents?

**Comment by vangheem** [comment] 2015-07-22 17:51
Yes.

There was a lot of nasty magic going on with previous implantation. This is
much better.

**Comment by vangheem** [comment] 2015-07-22 18:14
@davisagli IMO, this is the way it should have always been. If you are writing logic to delete an object, you should only have to care about links if you elect to care about it. Link integrity is an editor feature, not a enforced system requirement.

I understand that the current link integrity also causes a lot of testing problems.

**Comment by thet** [comment] 2015-07-22 18:29
Also, the current link integrity feature makes events like ``ObjectWillBeRemovedEvent`` and ``ObjectRemovedEvent`` useless, because they are fired even before the delete confirmation dialog is confirmed (see: https://github.com/plone/Products.CMFPlone/issues/666 , never mind the special issue number).
I agree with @vangheem  position, that linkintegrity checking is very useful for the UI, but should be used only explicitly when deleting programmatically.

**Comment by pbauer** [comment] 2015-07-23 15:26
I suppose it would be possible to keep the old logic (intercept the request on delete) and still migrate to zc.relation to drop the AT-dependency. But IMHO the proposed new behavior is much cleaner. I think that @vangheem hit the spot when saying "Link integrity is an editor feature, not a enforced system requirement." 

Link-integrity-checking is integrated when deleting single or more items and also checks if deleting children creates breaches. 

It would be nice if someone could look over the zc.relation-related code: 

- We do not store any information of the objects themselves, only in the catalog of zc.relation since the source for the relation is persisted in the textfields. I think that is ok, but maybe there are other opinions.
- Updating relations first unpacks all relations and removes them from the catalog before setting them anew. 

It is not the package with the most accessible api...

**Comment by hvelarde** [comment] 2015-07-23 19:07
it should be nice to add an option to `plone.api.content.delete` in order to check link integrity.

**Comment by pbauer** [comment] 2015-07-23 21:48
The plip-job (http://jenkins.plone.org/view/PLIPs/job/plip-698-linkintegrity/) is currently failing miserably. Anyone who could help would be more than welcome.

**Comment by jensens** [comment] 2015-07-28 20:08
we have to get rid of the monkey patches. too much magic added for this feature.
Im my opinion it is enough to check on ui interaction, so patching manage_delObjects and the response goes too far.

+1 to add a general check facility (utility interface available in CMFPlone, implementation in here) and use it in plone.api and all places in plone core where content is deleted through UI interaction.

**Comment by pbauer** [comment] 2015-08-01 13:21
Personally I think Plone 5 should not ship without Linkintegrity even though the framework-team decided to do so (https://github.com/plone/Products.CMFPlone/issues/255#issuecomment-66893411). Therefore I put in some work here but need some decisions and feedback from the framework-team regarding this PLIP.

- The core linkintegrity-feature (creation of relations beween objects that link to each other) is always enabled for ``Products.Archetypes.interfaces.IBaseObject`` and ``plone.app.relationfield.interfaces.IDexterityHasRelations`` (a marker for ``plone.dexterity.content.DexterityContent``). We could change it that these relations are only created and updated when linkintegrity is enabled (plone.app.linkintegrity.utils.linkintegrity_enabled). I'm against that since that will lead to a inconsistent linkintegrity-states (which can be fixed with @@updateLinkIntegrityInformation). Agreed?

- The above behavior introduces the intid- and zc.relation-catalogs as dependencies for AT (they are already a dependencies for DX). Some tests that don't have these fail. We could do one or more of the following:

 1. Add plone.app.intid and plone.app.relationfield to dependencies of CMFPlone
 2. Add plone.app.intid and plone.app.relationfield to PLONE_FIXTURE
 3. Install intid- and relationcatalog in setuphandler of Archetypes
 4. Add plone.app.intid and plone.app.relationfield to dependencies of Archetypes
 5. Add the intid- and relations-catalog in all tests that fail without them
 6. Add a profile to plone.app.linkintegrity with a dependency on plone.app.intid and a setuphandler to install the relations-catalog (which also installs the catalogs). Linkintegrity only needs plone.app.intid and reference-catalog but AFAIK none of the other features of plone.app.relationfield). Then add plone.app.linkintegrity to the dependencies of CMFPlone.

  I experimented with 1. which fixed 72 tests (18 still fail) in the plip job http://jenkins.plone.org/view/PLIPs/job/plip-698-linkintegrity but I have no strong opinion on that.

- Please decide if we can keep the removal of the request-interception and replace it with a parameter to ``plone.api.content.delete``. If I understand it right most people would favor the default to check for linkintegrity and a option to ignore it like ``def delete(obj=None, objects=None, ignore_linkintegrity=False)``. A breach could by default raise a LinkIntegrityNotificationException.

**Comment by jensens** [comment] 2015-08-03 09:21
overall +1. 

May you explain why we need (i)? Is it not enough to have ``plone.app.intid`` and ``plone.app.relationfield`` as deps of ``plone.app.linkintegrity`` and depend on p.a.l? Declaring deps where they apply feels cleaner to me.

checks are needed also in
https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/actions.py#L70
and
https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/delete.py#L59
Question is, if plone.app.content may be turned into a consumer of plone.api and uses its functions, since plone.api does not need anything from plone.app.content (afaik).

**Comment by pbauer** [comment] 2015-08-03 13:02
@jensens (i) is just an option that would allow us to leave p.a.linkintegrity without a profile. I agree that adding a profile and the dependencies in p.a.linkintegrity sounds much saner.

**Comment by pbauer** [comment] 2015-08-07 13:20
I did what @jensens proposed and fixed all the test failures (The build is still runnning but I am hopeful http://jenkins.plone.org/view/PLIPs/job/plip-698-linkintegrity). Someone needs to review this.

This plip introduces a new dependency on intid-catalog and zc.relation-catalog for Archetypes-objects. I'm not sure if these two are alread installed by some upgrade-step when migrating from 4 to 5. Does anyone know or do I have to try to find out?

**Comment by vangheem** [comment] 2015-08-07 15:22
I thought archetypes objects shared the same catalog as dexterity objects. I don't think there is any necessary upgrade except for rebuilding the link integrity relations(which should be an additional manual step IMO).

**Comment by pbauer** [comment] 2015-08-07 15:41
AT and DX share the same catalog for "normal" brains, but relations between objects are stored in different catalogs for Archetypes and Dexterity (reference_catalog in ``Products.Archetypes.ReferenceEngine.ReferenceCatalog`` vs. zc.relation-catalog in ``zc.relation.catalog.Catalog``). The whole point of the plip is to move Linkintegrity-relations to the zc.relation-catalog to drop the hard Archetypes-dependency for Plone 5. The simplification is a secondary thing.

Linkintegrity-relations are automatically migrated when migrating AT-content to DX. For types that are not migrated to Dexterity the solution is to either use the upgrade-step ``plone.app.linkintegrity.upgrades.migrate_linkintegrity_relations`` to only update those that are still in the reference_catalog or the view ``@@updateLinkIntegrityInformation`` to check **all** content in the portal for linkintegrity-relations. I propose to add a call of the first to plone.app.upgrade.

**Comment by vangheem** [comment] 2015-08-07 15:57
Correct, that's not what I'm referring to. I'm talking about zc.relation and how I don't think there is any upgrade step because intid and zc.relation catalog are already installed.

I'm indifferent on what we do about upgrade steps. Anything really heavy and that could take a long time is error prone or servers run out of memory, etc.

**Comment by hvelarde** [comment] 2015-08-10 18:59
we'll need to update this also: http://docs.plone.org/develop/plone/content/deleting.html#bypassing-link-integrity-check

**Comment by pbauer** [comment] 2015-08-11 22:04
Progress:
- Linkintegrity-notification are now working when deleting stuff in folder_contents.
- The api has be sanitized 
- We now ignore internal breaches (breached orginiating from objects that will also be deleted).
- We have working robot-tests in CMFPlone

What is missing:
- a parameter in plone.api's api.content.delete
- updated documentation

I will only start working on these two tasks if this PLIP will is be merged for Plone 5. So please, dear FWT say something!   

Also: @davisagli dug out some unfinished code (https://github.com/davisagli/Products.RelationIndex) that might allow us to replace the additional catalogs (zc.relation, reference_catalog) with a relatively simple index in the portal_catalog that would work for AT and DX. We will drop hard dependencies on uid_catalog and reference_catalog with p5 but also dropping hard dependencies on intid_catalog and zc.relation-catalog seems to be a good idea... It needs some more work though.
 https://github.com/davisagli/Products.RelationIndex

**Comment by jensens** [comment] 2015-08-12 08:28
I added the PLIP now to the offical spread sheet as submitted: 
https://docs.google.com/spreadsheets/d/15Cut73TS5l_x8djkxNre5k8fd7haGC5OOSGigtL2drQ/edit?usp=sharing

Discussion happens in next FWT meeting.

My opinion overall: +1 - this looks solid

Changing the catalogs and api is indeed for 5.1, too much in beta.
Since this is an feature we already had in 4.3 I dont feel its a problem to re-add the feature while beta.

**Comment by hvelarde** [comment] 2015-08-12 13:59
awesome work! :beers:

**Comment by pbauer** [comment] 2015-08-21 12:55
I updated the docs of plone.app.linkintegrity: https://github.com/plone/plone.app.linkintegrity/blob/plone5/README.rst

**Comment by pbauer** [comment] 2015-08-23 15:33
I did not yet add changenotes to most pull-request since that makes rebasing much easier). I will do that when merge-time comes.

**Comment by pbauer** [comment] 2015-08-25 18:16
Fixed with https://github.com/plone/plone.app.linkintegrity/pull/22

**Closed by pbauer** 2015-08-25 18:16 UTC
Labels: PLIP
