### ISSUE TITLE
Resource Registry is missing resources in production mode when expressions are used

### ISSUE THREAD

**Issue by MrTango** [plone/Products.CMFPlone#3789] opened 2023-05-24 15:10 UTC
### What I did:

register a resource bundle with an expression like:

``python:object.portal_type == 'File'``

and make sure that the resource registry is in production mode.

### What I expect to happen:

The resource bundles should be loaded.

### What actually happened:

The resource bundles with the expression are missing.

### What version of Plone/ Addons I am using:

Plone 6.0.4

**Comment by MrTango** [comment] 2023-07-05 16:08
Still present in 6.0.6

**Comment by krissik** [comment] 2023-07-17 08:14
I have the same problem

**Comment by krissik** [comment] 2023-08-10 06:05
I can confirm the issue. 
After disabling production mode + page reload the bundle is present. But after enabling production mode it is gone again.
But it might be more chaotic ...

**Comment by 1letter** [comment] 2023-08-11 17:43
I investigate the Problem, thats what i found:

- Requirement: this condition `python:object.portal_type == 'File'`
- tested on multilingual entry, because it's only a css file and not so much is broken
- for test three browser tabs (resourceregistry-controlpanel, a folder view and a file view) are needed

First Test

1. Start the instance in Prod-Mode
2. set the condition in the `@@resourceregistry-controlpanel` in production mode
3. go to the folder view tab and load the page -> multilingual.css is not loaded (means the condition works)
4. got to the file view tab and load the page-> multilingual.css is not loaded (means the condition works because in the ram cache is a `False` Value from Point 3)

Second Test

1. Start the instance in Prod-Mode
2. set the condition in the `@@resourceregistry-controlpanel` in production mode
3. go to the file view tab and load the page -> multilingual.css is loaded (means the condition works)
4. got to the folder view tab and load the page-> multilingual.css is loaded (means the condition works because in the ram cache  is a  `True` Value from Point 3)

Now i search the code piece where the resources loaded (from the cache) I think the calculation of the cache key is not right.

**Comment by petschki** [comment] 2023-09-20 12:45
any news on this?

**Comment by 1letter** [comment] 2023-09-20 14:29
@petschki no, sorry. I died during the research.

**Comment by petschki** [comment] 2023-09-20 14:49
Hopefully not! 😅 I'll try to take a look at this too...

**Comment by petschki** [comment] 2023-09-21 12:17
@tlotze you're right ... the cachekey was always rendered on portal root so no distinction between context. I've fixed that here #3844

**Comment by petschki** [comment] 2024-12-11 14:37
closed by https://github.com/plone/Products.CMFPlone/pull/3900

**Closed by petschki** 2024-12-11 14:37 UTC
Labels: 01 type: bug
