### ISSUE TITLE
Huge scrollable white area below Plone footer if you are logged in (in Plone 6)

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3411] opened 2022-01-25 17:04 UTC
- Plone 6.0a2
- default site
- logged in as Manager
-> a huge scrollable empty white area is visable under the footer

<img width="1509" alt="Bildschirmfoto 2022-01-25 um 18 01 36" src="https://user-images.githubusercontent.com/594239/151025787-b399a115-d207-4a72-a84e-d67fa2bf610b.png">

**Comment by rohnsha0** [comment] 2022-09-20 12:39
The issue is fixed in latest build

**Closed by rohnsha0** 2022-09-20 12:39 UTC
Labels: 01 type: bug
