### ISSUE TITLE
Plone 5.2 tests on Jenkins are hanging sometimes

### ISSUE THREAD

**Issue by jensens** [plone/Products.CMFPlone#2493] opened 2018-08-07 17:53 UTC
With Plone 5.2 sometimes we got the following error in Jenkins. Test hangs until some timeout drops in. This does not happen every time.

Any idea whats going on here?

cc @plone/testing-team

```
**Running plone.restapi.testing.PloneRestApiDXLayerFreeze:Functional tests:
  Tear down plone.restapi.testing.PloneRestApiATLayer:Integration in 0.000 seconds.
  Tear down plone.restapi.testing.PloneRestApiATLayer in 0.005 seconds.
  Set up plone.restapi.testing.FreezeTimeFixture in 0.000 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.391 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.416 seconds.
  Set up plone.restapi.testing.PloneRestApiDXLayer in 0.882 seconds.
  Set up plone.testing.z2.ZServer /home/jenkins/workspace/pull-request-5.2@2/src/plone.testing/src/plone/testing/z2.py:1028: DeprecationWarning: zhttp_server is deprecated. Please import from ZServer.HTTPServer
  from ZServer import zhttp_server, zhttp_handler, logger
/home/jenkins/workspace/pull-request-5.2@2/src/plone.testing/src/plone/testing/z2.py:1028: DeprecationWarning: zhttp_handler is deprecated. Please import from ZServer.HTTPServer
  from ZServer import zhttp_server, zhttp_handler, logger
/home/jenkins/workspace/pull-request-5.2@2/src/plone.testing/src/plone/testing/z2.py:1028: DeprecationWarning: logger is deprecated. Please import from ZServer.medusa
  from ZServer import zhttp_server, zhttp_handler, logger
in 0.506 seconds.
  Set up plone.restapi.testing.PloneRestApiDXLayerFreeze:Functional in 0.000 seconds.
/home/jenkins/.buildout/eggs/ZServer-4.0b1-py2.7.egg/ZServer/PubCore/ZServerPublisher.py:22: DeprecationWarning: publish_module is deprecated. Please import from ZServer.ZPublisher.Publish.
  from ZPublisher.Publish import publish_module
Traceback (most recent call last):
  File "/home/jenkins/workspace/pull-request-5.2@2/bin/test", line 438, in <module>
    '--test-path', '/home/jenkins/.buildout/eggs/zope.globalrequest-1.4-py2.7.egg',
  File "/home/jenkins/.buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 60, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/jenkins/.buildout/eggs/collective.xmltestreport-1.3.4-py2.7.egg/collective/xmltestreport/runner.py", line 73, in run_internal
    runner.run()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py2.7.egg/zope/testrunner/runner.py", line 189, in run
    self.run_tests()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py2.7.egg/zope/testrunner/runner.py", line 291, in run_tests
    self.skipped, self.import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py2.7.egg/zope/testrunner/runner.py", line 460, in run_layer
    import_errors)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py2.7.egg/zope/testrunner/runner.py", line 383, in run_tests
    test(result)
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/srv/python2.7/lib/python2.7/unittest/case.py", line 370, in run
    result.stopTest(self)
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py2.7.egg/zope/testrunner/runner.py", line 897, in stopTest
    self.testTearDown()
  File "/home/jenkins/.buildout/eggs/zope.testrunner-4.8.1-py2.7.egg/zope/testrunner/runner.py", line 821, in testTearDown
    layer.testTearDown()
  File "/home/jenkins/workspace/pull-request-5.2@2/src/plone.app.testing/plone/app/testing/layers.py", line 288, in testTearDown
    super(PloneTestLifecycle, self).testTearDown()
  File "/home/jenkins/workspace/pull-request-5.2@2/src/plone.testing/src/plone/testing/z2.py", line 950, in testTearDown
    self['zodbDB'].close()
  File "/home/jenkins/.buildout/eggs/ZODB-5.4.0-py2.7.egg/ZODB/DB.py", line 651, in close
    @self._connectionMap
  File "/home/jenkins/.buildout/eggs/ZODB-5.4.0-py2.7.egg/ZODB/DB.py", line 518, in _connectionMap
    self.pool.map(f)
  File "/home/jenkins/.buildout/eggs/ZODB-5.4.0-py2.7.egg/ZODB/DB.py", line 213, in map
    self.all.map(f)
  File "/home/jenkins/.buildout/eggs/transaction-2.2.1-py2.7.egg/transaction/weakset.py", line 62, in map
    f(elt)
  File "/home/jenkins/.buildout/eggs/ZODB-5.4.0-py2.7.egg/ZODB/DB.py", line 659, in _
    conn._release_resources()
  File "/home/jenkins/.buildout/eggs/ZODB-5.4.0-py2.7.egg/ZODB/Connection.py", line 948, in _release_resources
    c.close(False)
  File "/home/jenkins/.buildout/eggs/ZODB-5.4.0-py2.7.egg/ZODB/Connection.py", line 304, in close
    self.transaction_manager.unregisterSynch(self)
  File "/home/jenkins/.buildout/eggs/transaction-2.2.1-py2.7.egg/transaction/_manager.py", line 106, in unregisterSynch
    self._synchs.remove(synch)
  File "/home/jenkins/.buildout/eggs/transaction-2.2.1-py2.7.egg/transaction/weakset.py", line 51, in remove
    del self.data[id(obj)]
  File "/srv/python2.7/lib/python2.7/weakref.py", line 92, in __delitem__
    del self.data[key]
KeyError: 140183057419984**
```

This is from here: https://jenkins.plone.org/job/pull-request-5.2/1003/console

**Comment by davisagli** [comment] 2018-08-08 03:27
See https://github.com/zopefoundation/ZODB/issues/208 and https://github.com/plone/plone.restapi/issues/558

**Comment by sunew** [comment] 2018-08-14 16:59
and see https://github.com/plone/Products.CMFPlone/issues/2455

**Comment by sunew** [comment] 2018-09-15 08:49
Closing as duplicate of #2455

**Closed by sunew** 2018-09-15 08:49 UTC
Labels: 01 type: bug, 12 prio: high, 21 status: confirmed
