### ISSUE TITLE
Upgrade to latest setuptools/zc.buildout versions.

### ISSUE THREAD

**Issue by tisto** [plone/Products.CMFPlone#403] opened 2015-03-17 15:31 UTC
cc @gotcha

**Comment by tisto** [comment] 2015-03-17 18:34
Upgrading to latest setuptools version leads to 4 test failures in buildout.coredev:

plone.app.upgrade:

```
Running plone.app.testing.bbb.PloneTestCase:Functional tests:
  Tear down plone.app.relationfield.tests.test_marshall.UnitTestLayer in 0.000 seconds.
  Set up plone.testing.zca.LayerCleanup in 0.002 seconds.
  Set up plone.testing.z2.Startup in 0.095 seconds.
  Set up plone.app.testing.layers.PloneFixture in 8.555 seconds.
  Set up plone.app.testing.bbb.PloneTestCaseFixture in 2.224 seconds.
  Set up plone.app.testing.bbb.PloneTestCase:Functional in 0.000 seconds.
/home/jenkins/.buildout/eggs/Products.CMFCore-2.2.8-py2.7.egg/Products/CMFCore/DirectoryView.py:493: UserWarning: DirectoryView classic_ecmascript refers to a non-existing path 'plonetheme.classic:skins/classic_ecmascript'
  (self.id, reg_key), UserWarning)


Failure in test testDoUpgrades (plone.app.upgrade.tests.test_upgrade.TestUpgrade)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-setuptools@2/src/plone.app.upgrade/plone/app/upgrade/tests/test_upgrade.py", line 62, in testDoUpgrades
    self.assertEqual(last, current)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 755, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python2.7/unittest/case.py", line 726, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 412, in fail
    raise self.failureException(msg)
AssertionError: Tuples differ: ('4001',) != (u'5004',)

First differing element 0:
4001
5004

- ('4001',)
+ (u'5004',)
```

Products.CMFPlone:

```

Failure in test testDoUpgrades (Products.CMFPlone.tests.testMigrationTool.TestMigrationTool)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-setuptools@2/src/Products.CMFPlone/Products/CMFPlone/tests/testMigrationTool.py", line 59, in testDoUpgrades
    self.assertEqual(last, current)
  File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 755, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python2.7/unittest/case.py", line 726, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.7/unittest/case.py", line 412, in fail
    raise self.failureException(msg)
AssertionError: Tuples differ: ('4001',) != (u'5004',)

First differing element 0:
4001
5004

- ('4001',)
+ (u'5004',)



Failure in test testLatestUpgradeProfiles (Products.CMFPlone.tests.testQuickInstallerTool.TestQuickInstallerTool)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-setuptools@2/src/Products.CMFPlone/Products/CMFPlone/tests/testQuickInstallerTool.py", line 38, in testLatestUpgradeProfiles
    self.assertTrue(latest == '3')
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true



Failure in test testLatestUpgradeProfiles2 (Products.CMFPlone.tests.testQuickInstallerTool.TestQuickInstallerTool)
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/jenkins/workspace/plip-setuptools@2/src/Products.CMFPlone/Products/CMFPlone/tests/testQuickInstallerTool.py", line 46, in testLatestUpgradeProfiles2
    self.assertTrue(latest == '3')
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

  Ran 1392 tests with 4 failures, 0 errors and 0 skipped in 5 minutes 25.608 seconds.
```

**Comment by tisto** [comment] 2015-03-17 18:43
http://jenkins.plone.org/view/PLIPs/job/plip-setuptools/2/console

**Comment by tisto** [comment] 2015-03-17 19:02
The tests fail when upgrading from setuptools 7.0 to 8.0. setuptools 8.0 started to implement PEP 440:

http://pythonhosted.org//setuptools/history.html#id47

In Plone 4 we switched from a PEP 440 compliant versioning scheme (e.g. 3.2.3) to a non-compliant versioning scheme (e.g. 4001). Not sure what to do about this, since we can not revert it...

**Comment by davisagli** [comment] 2015-03-17 19:04
Versions like 4001 are just the GenericSetup profile version, not the egg version. Maybe the problem is that GenericSetup uses the API from setuptools to compare profile versions, and we must change it to use its own function so that it's not affected by the change in setuptools?

**Comment by mauritsvanrees** [comment] 2015-04-03 22:10
Problem is in GenericSetup. yuppie did a preliminary fix on subversion trunk and I created a branch with a better fix. Not released yet and not merged yet. See the [cmf mailinglist](https://mail.zope.org/pipermail/zope-cmf/2015-March/031490.html).

**Comment by tisto** [comment] 2015-06-03 05:37
Done: https://github.com/plone/buildout.coredev/pull/82

**Comment by mauritsvanrees** [comment] 2015-09-16 10:16
Pull request was merged, current coredev has the latest greatest:
zc.buildout = 2.4.3
setuptools = 18.3.1

**Closed by mauritsvanrees** 2015-09-16 10:16 UTC
Labels: Sprint
