### ISSUE TITLE
Missing Upgrade Step in 5.1.4 or is to much registered?

### ISSUE THREAD

**Issue by 1letter** [plone/Products.CMFPlone#2637] opened 2018-11-27 18:45 UTC
#### What I did:
- Install Plain Latest Plone 5.1.4
- Go To portal_setup in ZMI
- i see an available upgrade step
- i run this step

#### What I expect to happen:
- an up-to-date Plone

#### What actually happened:
- a screen with a request, that i should update my plone

#### What version of Plone/ Addons I am using:
Plone 5.1.4

#### This is the Plain Installation
![screen1](https://user-images.githubusercontent.com/11072000/49103718-663de900-f27c-11e8-842a-00eb66a533a7.png)
#### This is the portal_setup Tool with an available Upgrade Step
![screen2](https://user-images.githubusercontent.com/11072000/49103728-69d17000-f27c-11e8-8a07-084c75b658af.png)
#### i select the Upgrade Step
![screen3](https://user-images.githubusercontent.com/11072000/49103733-6ccc6080-f27c-11e8-8ea3-7f51a40aac44.png)
#### it runs
![screen4](https://user-images.githubusercontent.com/11072000/49103740-6e962400-f27c-11e8-9574-8acdcabfb02d.png)
#### the profile stays at 5115, it should 5114 !?
![screen5](https://user-images.githubusercontent.com/11072000/49103742-71911480-f27c-11e8-9aeb-c19bf597a151.png)
#### the Management Screens after the upgrade Steps
![screen6](https://user-images.githubusercontent.com/11072000/49103744-73f36e80-f27c-11e8-969f-bebbfc38f934.png)
![screen7](https://user-images.githubusercontent.com/11072000/49103752-75bd3200-f27c-11e8-82b5-5ae51a75e6fc.png)

**Comment by ale-rt** [comment] 2018-11-30 15:54
I can confirm the issue. 
The issue cannot be reproduced when using the 5.1.x branch because there was a bump in the profile, which now is 5115.

CC @mauritsvanrees: I thought you were working on someway to not show "future upgrade steps"

**Comment by ale-rt** [comment] 2018-11-30 16:02
See also #2377

**Comment by mauritsvanrees** [comment] 2018-12-03 21:54
@ale-rt You have found the code that I worked on in #2377. That code is included in Plone 5.1.4. But it does not help for the `portal_setup` Upgrades page. Something similar should be done there, like you allude to in PR #2643. Maybe including an option 'Show future upgrades', next to 'Show old upgrades', would help.

I see there is some confusion in `plone.app.upgrade`. https://github.com/plone/plone.app.upgrade contains tags 2.0.17 and 2.0.18, but in both tags the `CHANGES.rst` has 2.0.16 as latest version. @esteele did something go wrong with `towncrier`?

@1letter The upgrade from 5114 to 5115 actually [does nothing](https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v51/configure.zcml#L279-L290). This might change in a later version, though I guess we should fix that. But for the moment, I would say it is better to go to the Upgrade tab, select CMFPlone, click on 'Show old upgrades', and in the Upgrade Step Group from 5113 to 5114 (near the bottom), select one or both steps (I would say: go for Miscellaneous) and click Upgrade.
Result would be that the CMFPlone profile has pending upgrades (from 5114 to 5115 as you saw), but that at least the profile version and filesystem version are both 5114, and you won't have the scary warnings.

**Comment by jensens** [comment] 2023-03-12 18:09
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Closed by jensens** 2023-03-12 18:09 UTC
