### ISSUE TITLE
Time selector in Plone 5 is not exact

### ISSUE THREAD

**Issue by tomgross** [plone/Products.CMFPlone#605] opened 2015-06-10 15:16 UTC
With the current time selector in Plone 5b2 it is only possible to select half hour time moments. For certain press releases, anniversaries  or other use cases it may be necessary to specify more exact moments (like 9:13) with the time selector widget.

**Comment by vangheem** [comment] 2015-07-02 18:25
Plone 4 also did not allow exact times(I think 5 minute increments) so this is not a regression.

**Comment by vangheem** [comment] 2015-07-02 18:27
oh wow, current widget only allows 30 minute increments though :(

**Comment by vangheem** [comment] 2015-07-02 18:28
We can adjust the increment level but I'm inclined to say we use drop downs for Hour/Minute/(am|pm) instead like the previous widget. The date widget is fine though.

**Comment by tomgross** [comment] 2015-07-03 11:05
I'm +0.5 with 5 min steps in a dropdown for Plone 5.0, if this is what we have in Plone 4.3 now and is easy to implement. Having something usable like http://keith-wood.name/timeEntry.html would be a plus in my optionion. This satisfies the user entering dates with the keyboard AND the user selecting time with mouse scroll.

**Comment by thet** [comment] 2015-07-03 13:01
I have a use case, where we need to provide exact time entries for events, e.g. for the time a train leaves.

However, my approach was to allow free keyboard entries additionally to the selection. There is even a option in pickadate for that:
```
  time: { editable: true },
```

With that, you can fill in any time you want. But the changes are lost and reset to something selected from the widget. I believe the problem is in the pattern implementation, but I didn't had the time to fix that.

**Comment by vangheem** [comment] 2015-07-03 13:16
I would prefer to use the existing widget if it can be made to work properly this way. I'll look into it.

**Comment by vangheem** [comment] 2015-07-03 14:26
I've spent some time looking into the pickadate time picker. I don't think it's going to work for us. Even in `editable: true` mode, it doesn't work very well. Not validated, hard to validate, hard to work with non-interval and interval times of the pickatime picker. It's just not worth trying to make it work the way we want.

I suggest we go with something like http://keith-wood.name/timeEntry.html

**Comment by vangheem** [comment] 2015-07-03 14:37
http://jdewit.github.io/bootstrap-timepicker/ is a nice one.

**Comment by vangheem** [comment] 2015-07-03 14:46
@thet if you can get `editable: true`, go for that. I spent some time on it and it seemed like a decent amount of work. Also, while you're working on it, pay attention to how behavior changes with `editable: true` when you upgrade to pickadate 3.5.6 which we should do.

I've spent about all the time I can digging into it.

For now, I'm going to upgrade to pickadate 3.5.6 and set the interval to "5" so we have parity with Plone 4.

**Comment by thet** [comment] 2015-07-03 15:22
i like the bootstrap timepicker - nice one.
i might be able to contribute on that next week or the week after that.

**Comment by vangheem** [comment] 2015-07-13 06:05
Closing this ticket as it's no longer a regression. Since time increments match what we had for Plone 5, I would recommend waiting to change the widget until 5.1. We need to finish up 5.0!

**Closed by vangheem** 2015-07-13 06:05 UTC
Labels: Regression, Sprint
