### ISSUE TITLE
Toolbar: Actions not accessible when in horizontal mode

### ISSUE THREAD

**Issue by jcerjak** [plone/Products.CMFPlone#481] opened 2015-05-03 10:59 UTC
Actions (Cut, Copy, Delete, ...) are not accessible, because there is no vertical scrollbar:
![horizontal-toolbar-actions](https://cloud.githubusercontent.com/assets/191024/7444754/ed842698-f192-11e4-8646-40784d8e1045.jpg)

**Comment by vangheem** [comment] 2015-07-13 04:43
Closing as duplicate of https://github.com/plone/Products.CMFPlone/issues/482

**Comment by vangheem** [comment] 2015-07-13 04:44
Close as duplicate of https://github.com/plone/Products.CMFPlone/issues/482 and https://github.com/plone/Products.CMFPlone/issues/529

**Closed by vangheem** 2015-07-13 04:43 UTC
Labels: Bug, PLIP 13787 - Barceloneta / MainTemplate, Sprint, UX Editor
