### ISSUE TITLE
Site title configuration isn't used in <title> viewlet

### ISSUE THREAD

**Issue by davilima6** [plone/Products.CMFPlone#1761] opened 2016-09-15 10:52 UTC
It's only used when accessing configlets, search results or management contexts (portlets, viewlets, sitemap etc). Regular content items display "Site" from `portal/title` so the problem seems to be that the ZMI property at site root isn't updated when saving `@@site-controlpanel` - as it used to happen in Plone 4.3.

Tested in Plone 5.0.5 and in coredev - 5.1b1.dev0 (5103).

**Comment by cmemery** [comment] 2017-05-07 14:30
For what it's worth, this looks to be an issue in plone.app.layout in TitleViewlet class. I fixed in my site using [the approach described here](http://www.coresoftwaregroup.com/blog/topics/TitleViewlet). I did this in a custom product rather than sending a PR, since I am not entirely sure this is the best approach. [Actual code change can be seen here](https://github.com/cmemery/plone.app.layout/compare/master...cmemery-patch-1?quick_pull=1#diff-ef434236738e5f4961f2c71eabacec53).

**Comment by cdw9** [comment] 2017-06-27 22:42
Note if you give your Plone site the same title as set in the registry, it will use it in the `<title>`. Go to the root of the Plone site in the ZMI, click on the properties tab, then fill in the title.

**Comment by cekk** [comment] 2017-07-03 11:36
The problem is that on Plone 4 the value was stored only in one point (site properties), and the controlpanel show/save the value from it.

On Plone 5 there are two different points: site properties and the registry.
Or we keep them in sync from both sides on every change (i can easily fix the registry part, but i need to see how ZMI forms works), or we remove one of them..do we really need both?

**Comment by hvelarde** [comment] 2017-07-03 13:47
site properties is deprecated and should not be used.

**Comment by malthe** [comment] 2017-10-25 08:38
The problem seems to be that the `PloneSite` object does not override the `Title()` method to pull the value of the registry via `ISiteSchema` interface.

**Comment by jensens** [comment] 2023-03-12 14:09
I close the issue, because it addresses Plone 5.1 which is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Closed by jensens** 2023-03-12 14:09 UTC
Labels: 02 type: regression, 99 tag: UX Site Admin
