### ISSUE TITLE
"Build" in Resource Registries still not working properly

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1136] opened 2015-10-05 12:28 UTC
Clicking on "Build" for a bundle still does not terminate (happens with latest Chrome and latest FF on Linux)

**Comment by vangheem** [comment] 2015-10-06 05:29
Is there an error in the browser console? What bundle are you trying to build? Are there customizations?

I can't reproduce in released Plone 5.0 or in coredev buildout in Chrome or Firefox.

**Comment by zopyx** [comment] 2015-10-06 06:07
I could reproduce the problem with a checkout of 

- git@github.com:xml-director/xmldirector.plonecore.git
- branch 'plone5'
- "make build5"

After creating a new Plone site with "XML Director Plone 5" profile I went to resources registries and added "xmldirector.plonecore" resource to the 'plone' bundle and clicked on the "build" button -> building takes forever, no JS console messages, no backend messages.

Possible some issues with my JS code but this should not lead to such a situation.

**Comment by jensens** [comment] 2015-11-23 08:20
iirc this was fixed, at least while JS-Training at Plone conference in Bucharest it worked after using latest buildout.coredev 5 - @thet may you confirm and close this issue if so?

**Comment by jensens** [comment] 2017-03-08 11:41
works here for me. also meanwhile the command-line variant works.

**Closed by jensens** 2017-03-08 11:41 UTC
Labels: 01 type: bug, 12 prio: high, 99 tag: resource registry
