### ISSUE TITLE
navbar with z-index: 10

### ISSUE THREAD

**Issue by paskyorg** [plone/Products.CMFPlone#2336] opened 2018-03-09 10:14 UTC
### What I did:

Click on toolbar options with submenus.

### What I expect to happen:

Open the submenu and display it correctly.

### What actually happened:

The navbar has z-index: 10 and it is on top.

### What version of Plone/ Addons I am using:

Version 5.1.0

![image](https://user-images.githubusercontent.com/1679533/37202547-0ecf9396-238b-11e8-8eb5-675e787b6b9c.png)

**Comment by sonawanemaitreya** [comment] 2018-03-30 18:22
When we minimise the window, whether we have set toolbar position side or top in 'Site Setup', same thing happens:
![screenshot from 2018-03-30 23-48-59](https://user-images.githubusercontent.com/33842949/38148745-5be835ca-3475-11e8-8fbe-07ef2cc2ddfb.png)

**Comment by Frankkyl** [comment] 2018-03-30 18:38
I thought this is same as #2307. I try to update the z-index to 2 for nav. But still no more comments on that case.

**Comment by vincentfretin** [comment] 2020-07-08 12:16
duplicate of https://github.com/plone/Products.CMFPlone/issues/2307

**Closed by vincentfretin** 2020-07-08 12:16 UTC
Labels: 01 type: bug, 21 status: confirmed
