### ISSUE TITLE
Duplicate site entries in "Plone is up and running" page

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#3160] opened 2020-08-03 08:02 UTC
One Plone installation shows up twice in the "Plone is up and running" page (Plone 5.2.1)

![screenshot-b89794ae93c2 ngrok io-2020 08 03-10_00_25](https://user-images.githubusercontent.com/594239/89159858-65407d00-d570-11ea-84d7-35bb4c0999c7.png)
![screenshot-b89794ae93c2 ngrok io-2020 08 03-10_00_10](https://user-images.githubusercontent.com/594239/89159860-6671aa00-d570-11ea-8e05-ea1f5c96bd8e.png)

**Comment by ale-rt** [comment] 2020-12-17 23:09
This is really funny, I never saw something like this :)
According to:
https://github.com/plone/Products.CMFPlone/blob/d71fc60c6a2087df0e714f7bd0a1ba13f14c2986/Products/CMFPlone/browser/admin.py#L58-L65
and:
https://github.com/plone/Products.CMFPlone/blob/d71fc60c6a2087df0e714f7bd0a1ba13f14c2986/Products/CMFPlone/browser/templates/plone-overview.pt#L80-L81
This might happen if you have a `Plone site` inside a `Folder` with the same id, but it does not seem to be the case.
Showing the path instead of the id would resolve the ambiguity (if this is the reason).

Do you still have this issue?
Has anybody else spotted this issue?

**Comment by jensens** [comment] 2023-03-12 16:32
After all no way to reproduce. I close this now. Please reopen if you can provide a way to reproduce.

**Closed by jensens** 2023-03-12 16:32 UTC
Labels: 01 type: bug
