### ISSUE TITLE
Visual overlap in TinyMCE image upload

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#898] opened 2015-09-09 15:03 UTC
![screenshot 2015-09-09 17 02 31](https://cloud.githubusercontent.com/assets/594239/9765473/a0c19bfa-5714-11e5-811c-7a8afdf94f0a.png)

**Comment by jensens** [comment] 2018-08-13 08:47
wow, this one is still true

**Comment by vincentfretin** [comment] 2020-07-08 11:27
duplicate of https://github.com/plone/Products.CMFPlone/issues/2533 which I fixed

**Closed by vincentfretin** 2020-07-08 11:27 UTC
Labels: 01 type: bug, 14 prio: low, 21 status: confirmed, 41 lvl: easy, 99 tag: UX Editor
