### ISSUE TITLE
Plone 5: portlet management: stacking of overlays confusing

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#717] opened 2015-07-18 11:13 UTC
New portlets management uses three stacked overlay windows. Two overlays are already confusing,
three are a usability pain. In particular the background of the two top-level overlays are identical and because the bottom and top overlay have the same width while the middle overlay has a certain horiztonal offset....this all looks very weird.

![screenshot-dev1 veit-schiele de 8080 2015-07-18 13-09-51](https://cloud.githubusercontent.com/assets/594239/8761366/6917dd1c-2d4e-11e5-9ab9-12b19e2c5436.png)

**Comment by vangheem** [comment] 2015-07-18 18:55
How did you get 3?

2 overlays was a compromise we made to make manage portlets usable without tons of page reloads. However, 3 overlays should not happen.

**Comment by djay** [comment] 2015-07-19 03:28
Does it really make it that much faster than havrinf the portlet manager in
a page? Perhaps there is a way to reload the contents without the frame
instead if its that much faster. Visually having something so big and
variable in length in a overlay doesn't work so well I think.

**Comment by vangheem** [comment] 2015-07-19 13:22
Duplicate of https://github.com/plone/Products.CMFPlone/issues/717

**Closed by vangheem** 2015-07-19 13:22 UTC

**Comment by vangheem** [comment] 2015-07-19 13:25
Duplicate of https://github.com/plone/Products.CMFPlone/issues/717

**Comment by fgrcon** [comment] 2015-11-29 11:59
duplicate of itself ?
