### ISSUE TITLE
Relative URL is added to links and images when using Plone 5 and Archetypes TinyMCE Widget

### ISSUE THREAD

**Issue by AdCastle** [plone/Products.CMFPlone#1764] opened 2016-09-16 14:43 UTC
Hi all,

I raised this on - https://community.plone.org/t/relative-urls-in-tinymcewidget-products-archetypes-1-11-2/2742

Issues is while using Plone 5 and Products.Archetypes-1.12.

When you save a page with the link the initial save has the href as /resolveuid/{UID} on the next save the href ../../../../{ID of item} though the reference is still in tacked the path shouldn't be exposed in the content. For example if you move the page around the the link is then broken or if page is the default content of the page then the URL is broken. Previously TinyMCE would always save the resolveuid and Dexterity currently does after each edit. I was wondering can this be done for Archetype content types to avoid broken links.

Also the relative URL which is created is sometimes a '../' too much it seems 

Cheers,
Adam

**Comment by davisagli** [comment] 2016-09-25 05:36
This probably needs a similar fix to https://github.com/plone/plone.app.widgets/pull/146 (which is for the Plone 4.x branch of plone.app.widgets). The problem is that the widget is loading a transformed version of the text rather than the raw version.

**Comment by AdCastle** [comment] 2016-10-17 11:10
Hi @davisagli, cheers for responding. Indeed, it seems to linked to this. I'll watch the plone.app.widgets release and test once that fix has been pushed,

**Comment by jensens** [comment] 2023-03-13 10:54
I close the issue, because it addresses a Plone version that is no longer supported. 
If you think this is wrong please reopen the issue and assign a matching milestone.

**Closed by jensens** 2023-03-13 10:54 UTC
