### ISSUE TITLE
Login by email should not be case sensitive

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFPlone#628] opened 2015-06-15 07:50 UTC
Some organizations - don't ask me why - use title case for their email addresses (Firstname.Lastname@organization.org)

I think it would be useful and make life easier to either lowercase the email at registration time or even better, make the login by email not case sensitive at all.

**Comment by vangheem** [comment] 2015-07-17 08:50
This is a duplicate of https://github.com/plone/Products.CMFPlone/issues/261

**Closed by vangheem** 2015-07-17 08:50 UTC
