### ISSUE TITLE
 Circular dependency between p.a.multilingual and Products.CMFPlone

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFPlone#3859] opened 2023-10-15 16:44 UTC
As `plone.app.multilingual` is being moved to being a _plone core add-on_, `CMFPlone` should stop importing from it, right? 🤔 

There are quite a few repositories were I can not enable the `circular` GHA due to this circular dependency being reported 😕 

Any takers? 😄

**Comment by mauritsvanrees** [comment] 2023-10-16 21:38
This is already fixed... in Plone 6.1.  Making plone.app.multilingual a core add-on served two purposes:


1. Not everyone needs this, so make the package optional (the `Plone` package on 6.1 will still pull it in).
2. Fix a circular dependency between the two packages.

So on 6.1 this is fixed, but the circular dependency remains on 6.0.  That is an open end that we did not tackle yet.

Some options:

* Give up on trying to find and fix circular imports in 6.0.  Change the circular imports check in plone/meta to use the 6.1 versions.  But then plone/meta may need to be smart enough to see if a package branch is being used on 6.0 or on 6.1.
* On the plone.app.multilingual 7.x branch remove `Products.CMFPlone` from the dependencies.  This will cause `z3c.dependencychecker` to complain, so add it to the `ignores`.

If the last item works, that would be fastest, so worth a shot.

**Comment by mauritsvanrees** [comment] 2023-10-17 20:46
Forget what I said. :-)

In 6.0 there is no problem.  `plone.app.multilingual` 7.x does not depend on CMFPlone.  Well: the code imports it, but we do not have it in `install_requires` and we let `z3c.dependencychecker` ignore it.  This is the last option I mentioned.

The problem is on 6.1.  And there it has long been solved, except for one thing: we need a release of CMFPlone and update the version on dist.plone.org/release/6.1-dev.

I will see if I can make an internal release.  It still feels slightly too early for an alpha, with some more stuff that needs to be arranged, and it would take too much time now.

**Comment by mauritsvanrees** [comment] 2023-10-17 21:28
We first need https://github.com/plone/Products.CMFPlone/pull/3861

**Comment by mauritsvanrees** [comment] 2023-10-18 14:34
Locally:

```
$ . .tox/circular/bin/activate
$ pip freeze | grep -i cmfplone
Products.CMFPlone==6.0.7
```

So the `circular` env does not seem to be using the constraints from 6.1-dev.

**Comment by gforcada** [comment] 2023-10-19 15:22
I'm afraid so, that we would need `mxdev` for such cases, `constrains.txt` or the logic to use it, does not allow to override new versions with development ones, that's the whole point of `mxdev`, or?

A fancy generator of constraints files that take into account your development packages so that pip can install them properly.

Maybe is worth to bring the topic back to `pip` developers?

**Comment by gforcada** [comment] 2023-10-19 15:34
Another solution would be to improve `pipforester` like https://github.com/collective/pipforester/issues/6

**Comment by jensens** [comment] 2024-06-12 09:42
The PLIP was merged and is closed now, so I close this one.

**Closed by jensens** 2024-06-12 09:42 UTC
