### ISSUE TITLE
Comment byline needs some styling

### ISSUE THREAD

**Issue by pabo3000** [plone/Products.CMFPlone#893] opened 2015-09-09 09:56 UTC
![comment_byline](https://cloud.githubusercontent.com/assets/918640/9758876/90d45f32-56e9-11e5-973a-7c7b674930ac.png)
Date should be in one line with Author. Perhaps there should be something like 'Added Sep 09, 2015 11:50 AM' or 'CreatedSep 09, 2015 11:50 AM'

**Comment by esteele** [comment] 2015-09-09 20:11
Duplicate of #764

**Closed by esteele** 2015-09-09 20:11 UTC
