### ISSUE TITLE
Opacity used on (portlet) overlays -> bad readability

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#731] opened 2015-07-19 14:12 UTC
The very thin font used for the help texts visually interferes with some artifacts of the overlay behind due the opacity defined for the background.

![screenshot 2015-07-19 16 10 07](https://cloud.githubusercontent.com/assets/594239/8766255/bbffb88c-2e30-11e5-98a6-523281f6bae8.png)

**Comment by vangheem** [comment] 2015-07-19 14:26
Have you read the comment here? https://github.com/plone/Products.CMFPlone/issues/728

closing as duplicate of https://github.com/plone/Products.CMFPlone/issues/728

**Closed by vangheem** 2015-07-19 14:26 UTC
