### ISSUE TITLE
Date shows in Chinese

### ISSUE THREAD

**Issue by espenmn** [plone/Products.CMFPlone#1028] opened 2015-09-18 13:03 UTC
1) add Plone site, set language to Norwegian
2) The date shows in Chinese.

I also tried:
1) Set language to english, and add norwegian... more fun (see screenshots)
2) Different settings of english / norwegian / norwegian bokmål

![skjermbilde 2015-09-18 kl 15 02 15](https://cloud.githubusercontent.com/assets/1069235/9959705/4bdc595a-5e16-11e5-9af3-d953ba0754dd.png)
![skjermbilde 2015-09-18 kl 15 02 07](https://cloud.githubusercontent.com/assets/1069235/9959703/4bd90f34-5e16-11e5-8361-ca579ac58b59.png)
![skjermbilde 2015-09-18 kl 15 01 35](https://cloud.githubusercontent.com/assets/1069235/9959707/4bddd78a-5e16-11e5-8c85-0363eb8111d3.png)
![skjermbilde 2015-09-18 kl 15 01 21](https://cloud.githubusercontent.com/assets/1069235/9959704/4bd9f6c4-5e16-11e5-8d6b-44d996c42a33.png)
![skjermbilde 2015-09-18 kl 15 01 12](https://cloud.githubusercontent.com/assets/1069235/9959708/4bde7730-5e16-11e5-8c07-edd8eb409d7d.png)
![skjermbilde 2015-09-18 kl 15 00 55](https://cloud.githubusercontent.com/assets/1069235/9959706/4bdd308c-5e16-11e5-89b6-e86e4dbbb438.png)
![skjermbilde 2015-09-18 kl 15 00 14](https://cloud.githubusercontent.com/assets/1069235/9959710/4bf027be-5e16-11e5-9e81-70a48dcee0d7.png)
![skjermbilde 2015-09-18 kl 14 59 59](https://cloud.githubusercontent.com/assets/1069235/9959709/4befafb4-5e16-11e5-90e9-6f7b30384629.png)

**Comment by polyester** [comment] 2015-09-18 17:50
confirmed; it probably has to do with either the pat-moment pattern or the underlying moment.js. Chinese is zh-TW, which is the last in the list of po files so the bug is somewhere there.

**Comment by polyester** [comment] 2015-09-19 12:55
update: site works as expected when creating a site in Nynorsk (languagecode: nn), it seems we introduced an 'overarching" no countrycode which does not exist for pat-moment (the pattern that creates the 'human readable times'. It then looses it and takes the alphabetically latest one, which happens to be zh-TW (Taiwanese Chinese).
Easiest fix: only allow language choices between Nynorsk and Bokmal, and not a fictitious overarching "no" language code.

**Comment by cillianderoiste** [comment] 2015-09-20 07:56
Since this also happens for other languages, I think another solution is to pass 'en' as a second, fallback parameter to moment.js so that it will use English if it can't find a suitable locale. I'll have a look.

**Comment by pbauer** [comment] 2015-09-20 21:44
Fixed by @cillianderoiste in https://github.com/plone/mockup/pull/586

**Closed by pbauer** 2015-09-20 21:44 UTC
Labels: Bug
