### ISSUE TITLE
Left menu gets empty when any link under 'Add new' is clicked

### ISSUE THREAD

**Issue by abhibansal530** [plone/Products.CMFPlone#1440] opened 2016-03-06 13:47 UTC
Before Add menu - 
![plone-before-add](https://cloud.githubusercontent.com/assets/11635486/13554518/01245670-e3d0-11e5-9abb-a6e010cba5b6.png)

After add-
![plone-after-add](https://cloud.githubusercontent.com/assets/11635486/13554521/0ca3267a-e3d0-11e5-8d54-b68d263658b0.png)

**Comment by prakharjoshi** [comment] 2016-03-06 14:25
That is a plone design. You will get the menu bar on the created pages. So its not a bug or issue. Its a design flow AFAIK.

**Comment by gforcada** [comment] 2016-03-06 14:44
@prakharjoshi right, closing it.

**Closed by gforcada** 2016-03-06 14:44 UTC
