### ISSUE TITLE
Advanced @@add-site layout

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#884] opened 2015-09-09 05:15 UTC
See screenshot...the positioning of the add-on descriptions appears weird.
![screenshot-dev1 veit-schiele de 8081 2015-09-09 07-14-34](https://cloud.githubusercontent.com/assets/594239/9753864/91a6ef82-56c2-11e5-890d-7009f0139fe5.png)

**Comment by esteele** [comment] 2015-09-09 20:08
Duplicate of #862

**Closed by esteele** 2015-09-09 20:08 UTC
