### ISSUE TITLE
Layout Events repeat popup

### ISSUE THREAD

**Issue by ltakens** [plone/Products.CMFPlone#672] opened 2015-07-13 13:17 UTC
![popup](https://cloud.githubusercontent.com/assets/12794611/8650288/09e025e6-2972-11e5-90bb-fda03ca61f47.png)
Input unnecessarily wide and labels not next to inputs

**Comment by pbauer** [comment] 2015-07-14 10:50
duplicate of https://github.com/plone/Products.CMFPlone/issues/655

**Closed by pbauer** 2015-07-14 10:50 UTC
