### ISSUE TITLE
Error Editing Theme TTW - Save Button

### ISSUE THREAD

**Issue by birdwell** [plone/Products.CMFPlone#594] opened 2015-06-03 16:08 UTC
When at: ++theme++barceloneta/@@theming-controlpanel-mapper and editing a file.
At the save of that file you get the following error,
![screenshot 2015-06-03 11 07 03](https://cloud.githubusercontent.com/assets/3323856/7965079/c908fb7a-09e0-11e5-8f78-de29c24acb64.png)

**Comment by vangheem** [comment] 2015-06-03 16:10
Does it still save? Looks like an unrelated error from the file editor trying to load css style mode.

\cc @obct537

**Comment by birdwell** [comment] 2015-06-03 16:11
I am not able to save an updates to css files TTW.

**Comment by birdwell** [comment] 2015-06-03 16:13
On my plone site and https://plone5.veit-schiele.de, when I try to make a change to anything. Both error logs are similar. 
![screenshot 2015-06-03 11 12 35](https://cloud.githubusercontent.com/assets/3323856/7965192/87ab2d0a-09e1-11e5-991a-a7ae5474588c.png)

**Comment by vangheem** [comment] 2015-06-03 16:15
@obct537 I thought we noticed these error but they didn't affect saving, etc?

**Comment by ebrehault** [comment] 2015-06-03 16:17
I do not know about your install, but the one on https://plone5.veit-schiele.de is not up-to-date.
You must have a fresh checkout of Mockup and re-generate the bundles.

**Comment by vangheem** [comment] 2015-06-03 16:21
What I notice is that current theme editor allows you to attempt to edit a file system theme.

@birdwell is it possible you're trying to edit the file system barceoneta theme instead of first copying the theme and then editing?

@obct537 can you fix the "Inspect theme" button being available for file system themes?

**Comment by obct537** [comment] 2015-06-03 16:24
Yeah, that last picture is just a weird issue with the Ace editor. I've never seen it cause any issues. 

The original issue is unusual though. I think the javascript error may be irrelevant (and I think @ebrehault is correct, because that's an error that *should* be fixed now). 

Oddly, I tested the saving, and it works, except for one specific CSS file. Python is saying something about "'ascii' codec can't decode byte 0xe2....". I've seen similar errors in the past when I wasn't converting between UTF-8 and unicode, maybe something similar is happening here. I'll take a look at plone.resourceeditor and see if I can't figure out what's causing that.

@vangheem Yeah, I can.

**Comment by birdwell** [comment] 2015-06-03 16:28
@vangheem I got the saving to work now by including latest mockup, and regenerating the bundles. 
However: 
@ebrehault I am getting an error when re-generating thememapper:
GET http://localhost:8080/CCMF/++plone++static/components/dropzone/downloads/dropzone-amd-module.js 404 (Not Found)
I was able to get the latest mockup version.

**Comment by vangheem** [comment] 2015-06-03 16:31
@ebrehault shouldn't need to use a clone of mockup to be able to generate bundles. Plone ships with a packaged version of mockup.

**Comment by vangheem** [comment] 2015-06-03 16:40
@birdwell thanks. I can confirm that the resource is referenced incorrectly.

Can you test manually fixing by going to the resource registry and updating the js value from:

++plone++static/components/dropzone/dist/dropzone-amd-module.js

to:

++plone++static/components/dropzone/dist/dropzone-amd-module.js

I think we missed an upgrade step.

**Comment by vangheem** [comment] 2015-06-03 16:42
https://github.com/plone/plone.app.upgrade/commit/ff5d2245670ddc841957d1ffe5af4a0fff548af2

**Comment by birdwell** [comment] 2015-06-03 16:45
@vangheem, the rebundling of thememapper works with the updated js path.

**Closed** 2015-06-04 16:39 UTC
