### ISSUE TITLE
Collection -> sort_on "tag" option...does not make sense

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#942] opened 2015-09-11 13:41 UTC
Sorting on tags does not make much sense. In general it does not make any sense to sort on fields that are keyword indexes. I can not recall but I think there is even some code in ZCatalog checking for sorting on some kw index.

**Comment by polyester** [comment] 2015-09-12 22:36
Depends on usecase. For my usecase, it does makes sense, especially in combination with eea.facetedsearch to drill down.

**Comment by zopyx** [comment] 2015-09-13 08:09
See the screenshot why it it is broken.
'docs2' is shown before the second doc although the sort_on=tag should perhaps place the other doc first.

Tags in general must be considered unsorted and the Zcatalog does not support on a list of tags.

sort_on=tags must be implemented in my opinion by a post-Zcatalog-query step where the found docs are sorted based on their sorted listed of subjects...the current implementation just does not work and behaves randomly.

![Uploading collection — Site.png…]()

**Comment by hvelarde** [comment] 2015-09-14 14:20
@zopyx there's no screenshot here

**Comment by jensens** [comment] 2015-09-14 16:31
The problem is, Tags index  is a KeywordIndex. If we would want to sort on tags it would need either an own index ``sortable_tags`` (similar to sortable_title) or an post-query sorting - which blows up at some point and I dont want to have it in core. So indeed as @zopyx wrote, the current implementation does not make much sense.

**Comment by jensens** [comment] 2017-01-23 19:45
fixed in https://github.com/plone/plone.app.querystring/commit/4d06f1760d1cea2e925246d2446357ef84ca3907

**Closed by jensens** 2017-01-23 19:45 UTC
Labels: 01 type: bug
