### ISSUE TITLE
TinyMCE image dialog don't use settings from controlpanel

### ISSUE THREAD

**Issue by marwoe** [plone/Products.CMFPlone#1314] opened 2016-01-15 10:40 UTC
In a new Plone 5 Site the TinymCE image dialog don't use the settings for allowed sizes from the Image Handling controlpanel (Products.CMFPlone.interfaces.controlpanel.IImagingSchema).

Tested with Plone 5.0 and 5.0.2

![issue-allowed_sizes](https://cloud.githubusercontent.com/assets/16717620/12351268/ad3252f4-bb7c-11e5-8f24-090b537c22c9.jpg)

**Comment by hvelarde** [comment] 2016-01-15 11:54
I can confirm the same happens in Plone 4.3.

**Comment by agitator** [comment] 2016-08-03 22:22
@vangheem do you have an idea where tinymce get's the default sizes from?

**Comment by thet** [comment] 2016-08-27 06:41
Duplicate of: https://github.com/plone/Products.CMFPlone/issues/1717

**Closed by thet** 2016-08-27 06:41 UTC
Labels: 01 type: bug, 21 status: confirmed, 99 tag: UX Integrator/Themer
