### ISSUE TITLE
prefs_install_products_form should be sorted 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1697] opened 2016-07-27 13:38 UTC
The list of add-ons is unsorted. Sorting by displayed title would make a difference.

![screenshot-dev zopyx com 12020 2016-07-27 15-36-27](https://cloud.githubusercontent.com/assets/594239/17177104/165af912-5410-11e6-8e0e-132d43affa12.png)

**Comment by tmassman** [comment] 2016-11-21 16:29
This is a duplicate of #1400

**Closed** 2016-11-21 17:00 UTC
Labels: 04 type: enhancement

**Comment by thet** [comment] 2022-08-24 15:30
Done in https://github.com/plone/Products.CMFPlone/pull/3524
