### ISSUE TITLE
All content view Error - pls check

### ISSUE THREAD

**Issue by sudhan77** [plone/Products.CMFPlone#1120] opened 2015-10-01 19:49 UTC
got the following error in the All Content view. plone 5.0

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.Five.browser.metaconfigure, line 485, in __call__
Module Products.Five.browser.pagetemplatefile, line 125, in __call__
Module Products.Five.browser.pagetemplatefile, line 59, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 93, in __call__
Module z3c.pt.pagetemplate, line 163, in render
Module chameleon.zpt.template, line 258, in render
Module chameleon.template, line 191, in render
Module chameleon.template, line 171, in render
Module bc7e402303da83f4fbcbf2cccd638c70.py, line 278, in render
Module 3360cdeb5da61328c5f2c61d7c49f3ee.py, line 1223, in render_master
Module 3360cdeb5da61328c5f2c61d7c49f3ee.py, line 420, in render_content
Module bc7e402303da83f4fbcbf2cccd638c70.py, line 266, in __fill_content_core
Module bc7e402303da83f4fbcbf2cccd638c70.py, line 92, in render_content_core
Module five.pt.expressions, line 154, in __call__
Module five.pt.expressions, line 123, in traverse
Module OFS.Traversable, line 300, in unrestrictedTraverse
__traceback_info__: ([], '@@uuid')
AttributeError: @@uuid

 - Expression: "context/@@uuid"
 - Filename:   ... gg/plone/app/contenttypes/browser/templates/full_view.pt
 - Location:   (line 12: col 30)
 - Source:     tal:define="uuid context/@@uuid">
                                ^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7f58044a3bd0>
               views: <ViewMapper - at 0x7f5800994a50>
               modules: <instance - at 0x7f580b13f8c0>
               args: <tuple - at 0x7f58128cc050>
               here: <ImplicitAcquisitionWrapper CareerPlanning at 0x7f5805a4df00>
               user: <ImplicitAcquisitionWrapper - at 0x7f5801172aa0>
               nothing: <NoneType - at 0x91a870>
               container: <ImplicitAcquisitionWrapper CareerPlanning at 0x7f5805a4df00>
               request: <instance - at 0x7f580186ea28>
               wrapped_repeat: <SafeMapping - at 0x7f58011a5e10>
               traverse_subpath: <list - at 0x7f580186e248>
               default: <object - at 0x7f58127e8500>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper CareerPlanning at 0x7f5805a4df00>
               view: <SimpleViewClass from /opt/plone/buildout-cache/eggs/plone.app.contenttypes-1.2.4-py2.7.egg/plone/app/contenttypes/browser/templates/full_view.pt full_view at 0x7f5801be9290>
               translate: <function translate at 0x7f58016e4b18>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f58048bf0a0>
               options: {...} (0)
               target_language: <NoneType - at 0x91a870>

**Comment by pbauer** [comment] 2015-10-01 19:58
Thanks for reporting but this is already fixed.
This is the second time I had to close a duplicate of https://github.com/plone/Products.CMFPlone/issues/1109 (the first was https://github.com/plone/Products.CMFPlone/issues/1112). Please consider using the search-form provided by github (e.g. search for ``uuid`` or ``full_view``) before posting a issue.

**Closed by pbauer** 2015-10-01 19:58 UTC
