### ISSUE TITLE
Error Log Form raises insufficient-privileges Plone 6.0 

### ISSUE THREAD

**Issue by jmevissen** [plone/Products.CMFPlone#3358] opened 2021-11-18 09:22 UTC
### What I did:

Open "/prefs_error_log_form" on PloneRoot

### What I expect to happen:

To see the Error Log Form

### What actually happened:

"Insufficient Privileges" error

### What version of Plone/ Addons I am using:

Plone 6.0

**Comment by laulaz** [comment] 2021-11-18 10:50
This is a duplicate of #3335 😉

**Closed by laulaz** 2021-11-18 10:50 UTC
