### ISSUE TITLE
Problem to register new tool in "portal_controlpanel" and active news addons need to register icons in site setup

### ISSUE THREAD

**Issue by claytonc** [plone/Products.CMFPlone#1959] opened 2017-03-07 13:24 UTC
### What I did:

1 - Site Setup => Add-ons => check  "Workflow Policy Support (CMFPlacefulWorkflow)"  and clink in button Activate.

2 - ZMI => portal_controlpanel => register new tool

3 - Acess url: http://localhost:8080/Plone/portal_controlpanel/addAction

### What I expect to happen:

1 - Install add-on and show icon in Site Setup

2 - Register new tool in Site Seup

3 - BadRequest: ...  The parameter, <em>id</em>, was omitted from the request. ...

### What actually happened:

1 - Install add-on but not register icon in Site Setup not possibility configure Workflow Policy.

2 - Show page 404 "This page does not seem to exist… " .

3 - Show page 4040 "This page does not seem to exist…" 

### What version of Plone/ Addons I am using:

Plone 4.3.11 / Plone Default /  Unified Installer

01 - 
![01](https://cloud.githubusercontent.com/assets/1719539/23657865/ec37291c-031e-11e7-9d04-4952f6a93de1.png)

02 -
![02](https://cloud.githubusercontent.com/assets/1719539/23657871/f7ca7054-031e-11e7-8967-4114f131de37.png)

03 - 
![03](https://cloud.githubusercontent.com/assets/1719539/23657881/ff3c91aa-031e-11e7-843e-5f45d4c03832.png)

**Comment by mauritsvanrees** [comment] 2017-03-07 18:12
Partially confirmed.

- When I install CMFPlacefulWorkflow in coredev 4.3, the control panel icon is added just fine. It points to http://localhost:8080/Plone/prefs_workflow_localpolicies_form. Is that page loading fine for you?

- Adding via the ZMI does fail for me. And I see that I was the one who broke it, by removing a [docstring](https://github.com/plone/Products.CMFPlone/commit/a8a2a565bda3b6ed463923b01bfd78b115409495#diff-9b1fcc9f247a67d3ca6d4c15a5bf9707L231)... Sorry! I thought the `addAction` method did not need to be accessible directly via a url, but I was wrong. I will fix it.

**Comment by claytonc** [comment] 2017-03-07 19:32
@mauritsvanrees

In add-ons:

1 - CMFPlacefulWorkflow => Activate
2 - CMFPlacefulWorkflow => Deactivate
3 - CMFPlacefulWorkflow => Activate again, the icon not is added in control panel.

**Comment by claytonc** [comment] 2017-03-07 19:40
4 - CMFPlacefulWorkflow =>  Deactivate again => KeyError: 'portal_placeful_workflow'

**Comment by mauritsvanrees** [comment] 2017-03-08 10:19
Huh, that is odd. I can confirm it. So:

1. The first time you active `CMFPlacefulWorkflow` all is fine.
2. After deactivation everything seems okay too, but maybe something is not quite right at this point already.
3. A second activation finishes without error, but goes wrong: the control panel icon is not installed. And the `portal_placeful_workflow` tool is missing.
4. That results in a second deactivation failing.

There seems to be something wrong in the install or uninstall code of `CMFPlacefulWorkflow`. Or both.

**Comment by mauritsvanrees** [comment] 2017-03-08 10:41
Workaround:
- Go to `portal_setup` in the ZMI, and then the Import tab.
- Select profile "Workflow Policy Support (CMFPlacefulWorkflow)" (`profile-Products.CMFPlacefulWorkflow:CMFPlacefulWorkflow`).
- Select 'apply *all* profiles'. This makes sure the `base` dependency profile gets applied first.
- Click 'Import all steps'

**Comment by mauritsvanrees** [comment] 2022-08-24 09:59
Checked in 5.2 and 6.0.
I cannot reproduce the CMFPlacefulWorkflow problem, so that was fixed.
I *can* reproduce the problem that adding a control panel action in the ZMI does not work. My fix for that must have not made it to all branches. I have made PRs for 5.2 and 6.0.

**Closed** 2022-08-25 15:28 UTC
Labels: 01 type: bug, 99 tag: Plone 6.0
