### ISSUE TITLE
select2 html entities over escaped in Plone 5.2.5+

### ISSUE THREAD

**Issue by ewohnlich** [plone/Products.CMFPlone#3531] opened 2022-05-16 15:00 UTC
### What version of Plone/ Addons I am using: I tested on https://demo.plone.org (5.2.7) and on a local build with 5.2.4 and 5.2.5.

In 5.2.4 it worked as expected. In 5.2.5 and 5.2.7 (demo.plone.org) it did not. I would guess that the version of select2 was bumped as part of the 5.2.5 release. This should affect all html entities and all instances of SelectFieldWidget in most likelihood, but it easy to test with the Tags field out of the box.

**Comment by mauritsvanrees** [comment] 2022-05-19 13:12
Duplicate of https://github.com/plone/Products.CMFPlone/issues/3429

**Closed by mauritsvanrees** 2022-05-19 13:12 UTC
