### ISSUE TITLE
PLIP: merge collective.dexteritytextindexer into core

### ISSUE THREAD

**Issue by staeff** [plone/Products.CMFPlone#2780] opened 2019-02-28 10:14 UTC
## Abstract

[collective.dexteritytextindexer](https://github.com/collective/collective.dexteritytextindexer) provides a dynamic SearchableText indexer for dexterity content types. It makes it possible to index fields of multiple behaviors as SearchableText. The functionality of `collective.dexteritytextindexer` is something Plone could to offer OOTB.

## Motivation

By now each type needs its own SearchableText indexer to take several fields into account. 
For custom types or types which are components from different behaviors this is difficult a lot of work. 
It is counterintuitive to the idea of just configuring a type. 

- There has been already a preliminary discussion on this topic in a tickets on the repo itself. (https://github.com/collective/collective.dexteritytextindexer/issues/22). 
- This ticket illustrates how the inclusion in core could make things easier: https://github.com/plone/plone.app.dexterity/issues/237

## Proposal & Implementation

The new approach adds the information if a field is part of the SearchableText (or not) to the schema level.

## Deliverables

- [x] all significant commiters of this package need to agree and have (afaik) the Plone CLA signed.
- [x] move code over to matching core packages plip-branches
- [ ] probably it is a good idea to create a new BBB major release here with just deprecation imports from core.
- [ ] keep `collective.dexteritytextindexer` for Plone 5 installations with BBB code/imports?

## Participants

**Comment by tisto** [comment] 2019-04-16 13:08
@staeff your PLIP has been approved by the Plone framework team. Please go ahead with the implementation.

**Comment by jensens** [comment] 2020-09-24 18:56
@staeff Do you plan to work on this? I would really love to see this in core for Plone 6. If any help is needed please let us know.

**Comment by staeff** [comment] 2020-10-05 16:39
@jensens - sorry at the moment I am not able to work on it. Can the PLIP be changed, that someone else is taking it over?

**Comment by jensens** [comment] 2020-10-05 21:04
@staeff sure, remove youre name here - I can do an lookin-for-implementer announcement at community.plone.org

**Comment by jensens** [comment] 2022-02-28 10:47
We will resurrect this PLIP.

**Comment by zworkb** [comment] 2022-03-04 11:02
The following steps are planned to implement the PLIP and to integrate into the Plone 6.0 release:

- 0: prep:
   - new branch 'plip-2780' for plone.app.dexterity, plone.app.event:

- 1: repackage collective.dexteritytextindexer to plone.app.dexterity.textindexer
    - make everything work as before
    - remove deps on plone.api (converters.py)
    - remove zope.deferredimports from ```dexterityindexer.__init__```
    - remove six since we hav python 3 only
    - converters.py: remove conditional conditional imports

- 2: fix plone.app.event:
    - plone.app.event/dx/configure.zcml: remove     ```<adapter name="SearchableText" factory=".behaviors.searchable_text_indexer" /> ```
    make attrs in ```plone.app.event.behaviors.searchable_text_indexer``` searchable

    - check, if we can dump ```searchable_text_indexer``` completely
      
3: Further integration into ```plone.app.contenttypes``` is intended to come with a later Plone release
since it requires deep testing so that nothing breaks in existing code

**Comment by zworkb** [comment] 2022-03-29 17:18
You can try it out:

https://github.com/plone/buildout.coredev/tree/plip-2780

- clone it
-  $ make -f Makefile-plip-2780
- add the richtext behavior to event
- create an event, the richtext entry should now be found by a portal search

**Comment by zworkb** [comment] 2022-03-30 15:55
fixed it, have now added
https://github.com/plone/buildout.coredev/blob/6.0/plips/plip-2780-textindexer.cfg

steps are:

- `buildout -c plips/plip-2780-textindexer.cfg`
- add the richtext behavior to Event
- create an event, the richtext entry should now be found by a portal search

**Comment by pbauer** [comment] 2022-03-30 18:43
Builds for 3.7, 3.8 and 3.9:
https://jenkins.plone.org/job/pull-request-6.0-3.9/1004/
https://jenkins.plone.org/job/pull-request-6.0-3.8/1081/
https://jenkins.plone.org/job/pull-request-6.0-3.7/1085/

**Comment by pbauer** [comment] 2022-03-31 05:22
All tests are green

**Comment by zworkb** [comment] 2022-03-31 12:43
ive just seen that `plone.app.blocks` also steals SearchableText, so we have to fix that one too

**Comment by jensens** [comment] 2022-03-31 12:45
> ive just seen that `plone.app.blocks` also steals SearchableText, so we have to fix that one too, I'll go for that

this should not block the merge here

**Comment by zworkb** [comment] 2022-03-31 13:52
fixed plone.app.blocks: it indeed was textindexer-aware but of course only for collective.dexteritytextindexer.
it now respects both collective.dexteritytextindexer and p.a.d.textindexer

as a consequence textindexer works also if e.g. Mosaic is installed

**Comment by jensens** [comment] 2022-04-04 10:57
We did a cleanup/squash of the branches (and for a project for now I created backported branches pre ES6).

Now run Jenkins with:
```
https://github.com/plone/plone.app.dexterity/pull/344
https://github.com/plone/plone.app.contenttypes/pull/637
https://github.com/plone/plone.app.event/pull/354
https://github.com/plone/plone.app.upgrade/pull/282
```
Which I did here:
- https://jenkins.plone.org/job/pull-request-6.0-3.9/1027/
- https://jenkins.plone.org/job/pull-request-6.0-3.8/1101/
- https://jenkins.plone.org/job/pull-request-6.0-3.7/1109/

**Comment by pbauer** [comment] 2022-04-06 14:28
I fixes some failing tests by using named behaviors in tests.

New jenkins run:

* https://jenkins.plone.org/job/pull-request-6.0-3.7/1126/
* https://jenkins.plone.org/job/pull-request-6.0-3.8/1117/
* https://jenkins.plone.org/job/pull-request-6.0-3.9/1043/

**Comment by pbauer** [comment] 2022-04-06 19:06
Once more with feeling:

* https://jenkins.plone.org/job/pull-request-6.0-3.7/1132/
* https://jenkins.plone.org/job/pull-request-6.0-3.8/1123/
* https://jenkins.plone.org/job/pull-request-6.0-3.9/1049/

**Comment by pbauer** [comment] 2022-04-07 04:54
Three failing tests but I don't know why these fail since I cannot reproduce that locally:

* [plone.app.dexterity.textindexer.tests.test_schemaeditor.TestSchemaEditor.test_searchable_field_change_is_saved](https://jenkins.plone.org/job/pull-request-6.0-3.7/1132/testReport/junit/plone.app.dexterity.textindexer.tests.test_schemaeditor/TestSchemaEditor/test_searchable_field_change_is_saved/)
* [plone.app.dexterity.textindexer.tests.test_schemaeditor.TestSchemaEditor.test_searchable_field_is_disabled_by_default](https://jenkins.plone.org/job/pull-request-6.0-3.7/1132/testReport/junit/plone.app.dexterity.textindexer.tests.test_schemaeditor/TestSchemaEditor/test_searchable_field_is_disabled_by_default/)
* [plone.app.dexterity.textindexer.tests.test_schemaeditor.TestSchemaEditor.test_searchable_field_is_visible_with_behavior](https://jenkins.plone.org/job/pull-request-6.0-3.7/1132/testReport/junit/plone.app.dexterity.textindexer.tests.test_schemaeditor/TestSchemaEditor/test_searchable_field_is_visible_with_behavior/)

**Comment by pbauer** [comment] 2022-04-07 06:46
Oh my, someone changed the branch without updating the plip-config.

**Comment by pbauer** [comment] 2022-04-07 06:53
I fixed the config and updated the new branch of plone.app.dexterity with my test-fixes. Tests should pass now:

* https://jenkins.plone.org/job/pull-request-6.0-3.7/1136/
* https://jenkins.plone.org/job/pull-request-6.0-3.8/1127/
* https://jenkins.plone.org/job/pull-request-6.0-3.9/1053/

**Comment by pbauer** [comment] 2022-04-07 08:55
Dear https://github.com/orgs/plone/teams/framework-team, can we merge this?

**Comment by ale-rt** [comment] 2022-04-07 09:06
Thank you guys for implementing this one and @MrTango for checking it.
I briefly had a look and my idea is that this one should be merged.
I would say that:
1. if @MrTango is fine with the outcome of his review
2. if the other @plone/framework-team members do not object

Please wait at least one day before merging so that other members can jump in to the discussion :)

**Comment by pbauer** [comment] 2022-04-07 09:22
@ale-rt thanks for looking at it. I jumped ahead and merged the pull-requests. If someone objects I will revert. @MrTango is fine with the merge.

**Comment by MrTango** [comment] 2022-04-07 09:23
LGTM

**Closed** 2022-04-07 09:42 UTC
Labels: 03 type: feature (plip)
