### ISSUE TITLE
Improper resource URLs generated in Plone 5.0.5 

### ISSUE THREAD

**Issue by zopyx** [plone/Products.CMFPlone#1663] opened 2016-07-06 11:53 UTC
_Copied from [Community.plone.org](https://community.plone.org/t/improper-resource-urls-generated-in-plone-5-0-5/2426) for your convenience:_

I tried again to get my XML Director stuff flying on Plone 5.0 with the 5.0.5 release - however the nightmare with falling from one trap into another continues.

I have a [stylesheet](https://github.com/xml-director/xmldirector.plonecore/blob/master/xmldirector/plonecore/browser/resources/styles.css#L144-L183) referencing to some SVGs in my resource folder:

```
a.type-file:before {
background-image: url(++resource++xmldirector.plonecore/images/svg/raw2.svg) !important;
}

a.type-file[href*='.xml']:before {
background-image: url(++resource++xmldirector.plonecore/images/svg/xml5.svg) !important;
}

a.type-file[href*='.html']:before {
background-image: url(++resource++xmldirector.plonecore/images/svg/html9.svg) !important;
}

a.type-file[href*='.pdf']:before {
background-image: url(++resource++xmldirector.plonecore/images/svg/pdf19.svg) !important;
}

a.type-file[href*='.css']:before {
background-image: url(++resource++xmldirector.plonecore/images/svg/css5.svg) !important;
}
```

The stylesheet is configured using [cssregistry.xml:](https://github.com/xml-director/xmldirector.plonecore/blob/master/xmldirector/plonecore/profiles/default-51/cssregistry.xml)

```
<?xml version="1.0"?>
<object name="portal_css" meta_type="Stylesheets Registry">
 <stylesheet title="" cacheable="True" compression="safe" cookable="True"
    enabled="True"
    id="++resource++xmldirector.plonecore/styles.css" 
    media="screen" rel="stylesheet" rendering="link" />
</object>
```

However the resource files can not be loaded due to some improper URL.

<img src="https://community.plone.org/uploads/default/optimized/1X/4a0487e0970346b3a656c8a3582b2c9f6c392876_1_690x455.png">

**Where is this ++plone++production/++unique++/... prefix in the URL of the resource files coming from?**

**Comment by hvelarde** [comment] 2016-07-06 21:51
@ebrehault this seems to be related to your previous changes in the resource registry to fix the legacy bundle.

**Comment by hvelarde** [comment] 2016-07-07 20:59
maybe this is an stupid proposal but, anyway: has anybody on the @plone/framework-team though about the following possible implementation of the resources registries story:

* remove completely the legacy bundle and associated stuff from the new implementation
* bring back good old [Products.ResourceRegistries](https://github.com/plone/Products.ResourceRegistries) back into Plone 5.0 as a hard dependency (to be removed in Plone 5.1) to deal with old stuff

what we have with this?

* smaller, cleaner and easier to maintain code for the future
* Plone 5 do the stuff the new way but old way coexist in the same way it was before without any magic
* clear path for migration: in Plone > 5.0 we still will be able to use old Products.ResourceRegistries as a optional dependency

is that possible? do you want a PLIP?

**Comment by zopyx** [comment] 2016-07-13 14:56
Note that I was not suggesting to bring back the old cmf registries back.

**Comment by hvelarde** [comment] 2016-07-14 17:53
in my opinion what I'm proposing is what we should have done to get rid of the old resource registries in an orderly way:

* let's face it: the new resource registry was not tested enough before it was included in Plone; we didn't think about the implications for add-on developers and integrators and that leads to a low number of add-ons being compatible with Plone 5 and, because of that, a very low number of sites being migrated to Plone 5; adoption is slow and is going really slow; resource registries is one of the reasons for that
* Products.ResourceRegistries works; having old stuff using jsregistry.xml and cssregistry.xml there is already implemented
* new Plone legacy bundle is buggy and it has to keep support for old way of doing things; those things don't belong there
* resource consolidation is overrated, IMO; old resource registry works most of the time and you are able to serve a nice Plone site with very few resources; loading 1 or 3 JS files… 1 or 3 CSS files… things are not that bad and there are currently other ways to minimize the number of requests ([HTTP/2](https://http2.github.io/faq/) just to mention one); just to give you an example, on the sites we maintain we are able to easily get an A rating from [PageSpeed Insights](https://developers.google.com/speed/pagespeed/) and a B rating from [YSlow](http://yslow.org/) with very few work

I have no idea of the implications, but better now that later.

**Comment by zopyx** [comment] 2016-07-15 06:23
Not sure what the old resource registries would solve in the context of Plone 5?

Adding a single JS file directly inside a template without any registration may lead to the welcome RequireJS errors. So the old registries would blindly inject the JS scripts in the same way with the same risk of random breaking. The fundamental limitation (not sure if I am allowed to call it a flaw) is that dominance of the RequireJS approach is often not compatible with third-party JS modules. There has to be a clear, well-defined and under all circumstances _working_ way to have arbitrary JS code living side by side with stuff under the control of RequireJS. This is not a question how we register JS/CSS files (as bundles/resource or through the old CMF registries), the question is how both can live side by side without side-effects. 

Side rant: the current limitation of one JS file per resource is neither friendly nor approachable.some JS modules have one main JS module and other JS modules as plugins...you need to define multiple resource in this case because a resource is limited to one JS file per resource. I personally don't care why this limitation exist but the leads to a huge configuration overhead and verbose configuration with the result that the related XML snippets in registry.xml become much larger than related configurations in jsregistry.xml. Readabilty and easy approachability is king (from the integrators prospective and in particular from the prospective of not so advanced Plone devs).

**Comment by rodfersou** [comment] 2016-07-15 13:44
I get many dilemmas when I think about it...

The JavaScript we are used to write for Plone 4.x is not compatible with Plone 5.x.. it needs to be rewritten to support AMD, and RequireJS.  So the addons need to break compatibility and have two supported versions.. No easy way to make an upgrade step to reuse the old JS, and the registry will be different at all.

But.. we are thinking about to [use ReactJS instead of Backbone](https://github.com/plone/Products.CMFPlone/issues/1485).  And everywhere I study about ReactJS, they use another approach to work with Javascript modules.. they use Webpack, and Webpack figures out how to work with modules, and don't use RequireJS.

So I don't know if the case is to rewrite again our new registry to stop using RequireJS and Grunt in favor of using Webpack instead.

Or we are going to build a Frankenstein... Our way to manage resources will be disconnected with the way other places always do with ReactJS.. this means that if we get in trouble with something, it will be our problem, and we will not find help easy in the internet.

**Comment by rodfersou** [comment] 2016-07-15 14:29
In my opinion, our new resource registry should just:

* Concatenate the JS or CSS files already minified by every package when cook a package.  In development mode, you just use the ``<file>.js`` file instead of the ``<file>.min.js`` that every package should have.
* Dependencies of packages should be added in the ``setup.py`` file.
* Bundles are not needed.

This would make things more simple.

**Comment by keul** [comment] 2016-07-15 16:25
I don't think using webpack is the way to go... not now.

Webpack is amazing but it won't work with the Plone add-ons ecosystem, you need to have full control of your JavaScript sources. AMD is the only way to go right now.

**Comment by ebrehault** [comment] 2016-07-18 09:27
@zopyx this bug is due to my commit https://github.com/plone/Products.CMFPlone/commit/45bd7db88ce578a76e1510ef7fe720ce1fb17c37
That's what insert the ++production++ thing at the begining of each URLs.
I made that change so relative URLs are not broken when bundles are merged, and it works with local URLs, but not with ++resources++ URLs.
I need to fix that.

**Comment by ebrehault** [comment] 2016-07-18 09:50
@zopyx I got it. URLs prefixing works fine with bundles, but you have no bundle, you use cssregistry.xml. I need to dig a little bit more.

**Comment by keul** [comment] 2016-08-03 09:05
@ebrehault any news about this? I've a similar issue as @zopyx but *I'm using* a bundle (a simple bundle with a CSS inside, that want to refers to resouces defined somewhere else).

Rght now I need to define CSS with relative URLs like ../../++resource++foo/... but I'm only able to make CSS working in production mode **or** development mode.

😞

**Comment by ebrehault** [comment] 2016-08-03 22:57
@keul, well I haven't worked on this issue yet, but what you describe is a different issue (I have to admit I did not think about referencing external resources, I am afraid it will be quite complex to handle, but I will try to figure it out).

**Comment by keul** [comment] 2016-08-04 07:52
Thanks @ebrehault, much appreciated.

**Comment by displacedaussie** [comment] 2016-12-01 22:06
I ran into this yesterday and can confirm that @ebrehault's solution of turning off the `merge_with` option for the bundles helped for my more or less "default" site. I now have the following in my Plone 5 GS profiles:

```
<?xml version="1.0"?>
<registry>

  <!-- Bundles -->
  <records prefix="plone.bundles/plone"
            interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="merge_with"></value>
  </records>

  <records prefix="plone.bundles/plone-logged-in"
            interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="merge_with"></value>
  </records>

  <records prefix="plone.bundles/resourceregistry"
            interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="merge_with"></value>
  </records>

  <!-- bundle -->
  <records prefix="plone.bundles/thememapper"
           interface='Products.CMFPlone.interfaces.IBundleRegistry'>
    <value key="merge_with"></value>
  </records>

</registry>
```

**Comment by emansije** [comment] 2017-05-10 10:50
Sorry for the noob question, @displacedaussie, but how do I insert that XML in the GenericSetup?

**Comment by tkimnguyen** [comment] 2017-06-05 12:32
@emansije you'd have to include that XML in a file system add-on, though a very recent merge gives Plone the ability to import XML like that through the web.

**Comment by cekk** [comment] 2018-01-06 18:21
I had a similar issue too yesterday.
My situation was a Plone 5.1rc2 with updated mockup version (to fix a bug with a pattern).
To be able to see the mockup update in the site, i had to re-compile plone-logged-in from the control panel.

After compiling it, i had mockup patterns updated, but i lost tinymce button icons because there were some resources with a wrong url, for example:
http://localhost:8080/Plone/++plone++production/++unique++2018-01-05T17:32:55.304059/++plone++static/components/select2/select2.png

or a couple of fonts needed by plone-logged-in.css.

With @ebrehault and @displacedaussie trick, it seems to be fixed, but i don't know if this change will affect something else.

**Comment by pbauer** [comment] 2018-04-18 10:15
The same issue appeared on demo.plone.de with Plone 5.1.1. I worked around this with https://github.com/collective/demo.plone.de/commit/a1d41f5fed93b7e3cc09f01aef347d71749f1a60 but it needs a proper fix in the core.

**Comment by pbauer** [comment] 2018-04-18 10:28
In 5.1.2-pending i could not reprocide it any more. Can this be closed? @ebrehault

**Comment by ebrehault** [comment] 2018-04-18 11:04
@pbauer did you try to reproduce the original issue or the one described by @keul ?

**Comment by pbauer** [comment] 2018-04-18 12:05
@ebrehault I had the same issue as @cekk but with tinymce-icons in a clean instance: 

When running 5.1.1 in production I got requests to http://localhost:8082/Plone7/++plone++production/++unique++2018-04-18T13:49:25.560803/++plone++static/fonts/tinymce.ttf and http://localhost:8082/Plone7/++plone++production/++unique++2018-04-18T13:49:25.560803/++plone++static/fonts/tinymce.woff which do not exists so the icons in tinymce were broken. The workaround fixed these

In 5.1.2 the icons in tinymce work but Plone does not use a `tinymce.woff` and `tinymce.ttf` any more. The only font being loaded is roboto and that comes from http://localhost:8082/Plone8//++theme++barceloneta/less/roboto/roboto-regular.woff (yes there are two `//` in the url)

When I run in foreground the issue never appears. 

Since the fix might be due to a change in tinymce the issue might still be open.

**Comment by ebrehault** [comment] 2018-04-18 12:11
I think so, because I haven't seen any recent changes that could have fixed it.

**Comment by sunew** [comment] 2018-09-12 07:51
Issue can be reproduced on 5.1.3-pending

Reproduce:
On a site running with `instance start` (not in debug mode).
Go to resource registry, set in debug mode. Save. Set it back to production. Save.
Now you get 404's on:

https://cms.integrationsviden.dk/++plone++production/++unique++2018-09-11T17:21:00.926425/++plone++static/fonts/plone-fontello.woff 
https://cms.integrationsviden.dk/++plone++production/++unique++2018-09-11T17:21:00.926425/++plone++static/components/bootstrap/fonts/glyphicons-halflings-regular.woff2

**Comment by jensens** [comment] 2019-06-21 01:01
Afaik this was fixed. Please reopen if i am wrong.

**Closed by jensens** 2019-06-21 01:01 UTC
Labels: 02 type: regression, 12 prio: high, 21 status: confirmed

**Comment by scmos** [comment] 2020-04-29 22:15
Just like @displacedaussie I am trying to change the tags to <value key = "merge_with"> </value> but I am still with Improper resource URL
http://10.38.239.35:8084/Plone/++plone++production/++unique++2020-01-16T20:27:36.971913/++plone++static/fonts/plone-fontello.woff

However in TTW override way I edit the file default.css and change the local routes with ../../fonts and the error is corrected.

I am using 5.1.6 migrated from 5.1.5

Any suggestion to definitively solve?
