### ISSUE TITLE
AttributeError: @@uuid after Display -> All content

### ISSUE THREAD

**Issue by domruf** [plone/Products.CMFPlone#1112] opened 2015-09-30 10:55 UTC
I played a bit with Plone 5.
And after selecting "All content" in the Display menu on the page root I get AttributeError: @@uuid.
What makes this really bad is the fact that the whole menu stops working after this.
So I can even reverse the Display option.

**Comment by pbauer** [comment] 2015-09-30 11:04
Duplicate of https://github.com/plone/Products.CMFPlone/issues/1109. 
Also it is already fixed (I noticed the bug on demo.plone.de and deplyoed the fix there).

Workaound if you broke you site: gi to ``/select_default_view`` and select a different view.

**Closed by pbauer** 2015-09-30 11:04 UTC
