### ISSUE TITLE
plone.namedfile: Get rid of zope.app.file dependency

### ISSUE THREAD

**Issue by icemac** [plone/Products.CMFPlone#1594] opened 2016-05-20 09:25 UTC
Currently it is only a soft dependency. But:

* zope.app.file is really old and unmaintained (It still lives on [svn.zope.org](http://svn.zope.org/zope.app.file/)!)
* The last release was in [2010](https://pypi.python.org/pypi/zope.app.file/3.6.1#changes).
* Only one class of this package seems to be used by plone.namedfile.

If this is not the right issue tracker for this problem pease guide me. (plone.namedfile does not have its own one.)

**Comment by davisagli** [comment] 2016-05-21 16:00
Closing as a duplicate of https://github.com/plone/plone.namedfile/pull/20

tl;dr: This is not merely leftover code, but the soft dependency provides an important feature in the present, which is that if you load an old database with files that were stored persistently as zope.app.file chunks, they can still be read as non-broken objects.

**Closed by davisagli** 2016-05-21 16:00 UTC
