### ISSUE TITLE
modal dialogs are sized incorrectly on mobile devices

### ISSUE THREAD

**Issue by tkimnguyen** [plone/Products.CMFPlone#774] opened 2015-07-31 18:43 UTC
On iPhone 6 Plus and 5S (at least), the following modal dialogs are wider than the screen:
- [ ] login
- [ ] upload files
- [ ] TinyMCE Insert Image

See https://github.com/plone/Products.CMFPlone/issues/762 for screen shots. @plone/ux-team

**Comment by agitator** [comment] 2015-10-01 15:53
a problem on smaller screens in general

**Comment by envy7** [comment] 2017-03-05 05:06
@tkimnguyen can I work on this?

**Comment by tkimnguyen** [comment] 2017-03-05 05:22
@envy7 by all means! thanks :)

**Comment by envy7** [comment] 2017-03-05 06:38
I figured out what the problem was at least for the login modal and maybe the same thing applies for the other modals too, I wasn't able to recreate the issue for iphone 6 plus, the issue is arising cause the width is set to 26em with the font size as 14px, the width being 26*14 = 364px but iphone 5,4 have  screen widths of 320px, hence the overflow, i tried decreasing it to 20em for them and it looks good

![image](https://cloud.githubusercontent.com/assets/12188993/23585156/47aef196-019c-11e7-8956-5f23c99056d3.png)

**Comment by envy7** [comment] 2017-03-05 06:55
@tkimnguyen how should I move forward to this problem, write media queries for size of devices less than 364px or something else? I looked into the other modals too the same problem is there, the upload files modal had a max-width of 500px set, it has to be reduced.

**Comment by tkimnguyen** [comment] 2017-03-05 14:50
nice work @envy7  - perhaps @agitator has thoughts on how to proceed

**Comment by VerSooSet** [comment] 2017-03-05 23:07
It the same thing [1217](https://github.com/plone/Products.CMFPlone/issues/1217). In my view it solved this way too.

**Comment by nikandroff** [comment] 2017-03-06 14:54
Yes, https://github.com/plone/Products.CMFPlone/issues/1217 seems to be the same issue. Is not https://github.com/plone/Products.CMFPlone/issues/1217 a duplicate?

**Comment by agitator** [comment] 2017-03-06 16:58
@envy7 please check where to origin of the style attribute is - width as a style attribute problably comes from some javascript

**Comment by envy7** [comment] 2017-03-06 17:03
@agitator okay I'll check on it

**Comment by envy7** [comment] 2017-03-07 10:02
@agitator I found the function positionModal in plone-compiled.js which assigns the margin, padding, width etc.
modal dialog's width is assigned as self.options.width which in turn in defined as "" initially, and the width of the modal is not calculated anywhere. But in profiles/default/actions.xml I found this

    <property name="modal" type="text">{"prependContent": ".portalMessage", "title": "Log in", "width":        "26em", "actionOptions": {"redirectOnResponse": true}}</property>

This is also assigned to modal content's width.
Hence both 'plone-modal-content', 'plone-modal-dialog' are getting assigned width as 26em for all screen sizes.

**Comment by envy7** [comment] 2017-03-10 19:42
@agitator am I on the right track or is it something else entirely?

**Comment by tkimnguyen** [comment] 2017-03-11 14:28
@envy7 I'm not familiar enough to have an opinion, but it's great that you've dug into it so quickly! Maybe you can make a pull request – having something to look at may get others' attention more quickly.

**Comment by agitator** [comment] 2017-03-13 09:48
@envy7 maybe it's best if you add max-width-styles for the standard overlays in https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/modal.plone.less based on @plone-grid-float-breakpoint variable

@RobZoneNet @plone/ai-team opinions?

**Comment by davilima6** [comment] 2017-03-13 20:14
@agitator, I think this is a good strategy: mediaquery using the LESS variable breakpoint.

@envy7, notice you have to edit the source file and then generate `plone-compiled.js` by running the grunt script in ./bin/plone-compile-resources (see: https://docs.plone.org/adapt-and-extend/theming/resourceregistry.html#compiling-bundles)

**Comment by envy7** [comment] 2017-03-16 05:17
@agitator @tkimnguyen @davilima6 While using the resourceregistry-controlpanel I came across another modal sized incorrectly on mobile devices, I added media queries in https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/modal.plone.less using @plone-grid-float-breakpoint variable and fixed it, but it dosen't seem to fix the login modal size, and for upload files and TinyMCE insert image I need to make changes in the https://github.com/plone/mockup/tree/master/mockup/patterns right? cause I can't find anything in plonetheme.barceloneta in relation to them

incorrect:
![image](https://cloud.githubusercontent.com/assets/12188993/23982773/aad455d0-0a35-11e7-8391-59332e2138a3.png)

correct:
![image](https://cloud.githubusercontent.com/assets/12188993/23982768/9acc3856-0a35-11e7-9bd1-ff97c0ea7183.png)

**Comment by tkimnguyen** [comment] 2017-03-18 21:48
lol maybe this bug shouldn't have been tagged "easy" ... sorry @envy7 I can't really help you

**Comment by davisagli** [comment] 2022-08-24 22:48
I checked the listed modals in Plone 6 and they are working pretty well. I'd suggest creating more specific new issues for any remaining glitches.

**Closed by davisagli** 2022-08-24 22:48 UTC
Labels: 01 type: bug, 31 needs: help, 41 lvl: easy
