### ISSUE TITLE
Image Edit Possible Simple Rotation ?

### ISSUE THREAD

**Issue by bledwell** [plone/Products.CMFPlone#796] opened 2015-08-05 03:09 UTC
When someone goes to "edit" an image could a rotate clockwise be added? I don't think anything else necessarily should be added but I think a rotation would be helpful.
![ploneimageedit](https://cloud.githubusercontent.com/assets/4641090/9077574/5f0b4804-3af5-11e5-8b4f-474389704ac2.png)

**Comment by vangheem** [comment] 2015-08-05 10:38
This will need a PLIP. Won't make it into Plone 5.0.

**Comment by hvelarde** [comment] 2015-08-05 18:08
don't we have image transforms here like in Plone 4?

![selection_002](https://cloud.githubusercontent.com/assets/341393/9093655/b2f1498a-3b83-11e5-9cdb-e2d229499d0a.png)

please tell me we're not removing another feature because then that will be a regression.

**Comment by vangheem** [comment] 2015-08-05 18:41
Transform was an ATContentTypes thing--not sure that ever got re-implemented in dexterity. I know that plone 4 implementation is in Products.ATContentTypes.

**Comment by hvelarde** [comment] 2015-08-05 18:44
@vangheem that's from the core developer point of view; from the user point of view it don't matter if it was Archetypes of Dexterity… it was a feature that was there before and now is gone… is a regression and we need to fix it.

**Comment by pbauer** [comment] 2015-08-05 18:45
Duplicate of https://github.com/plone/plone.app.contenttypes/issues/32
See there for discussion of a implementation.

**Comment by vangheem** [comment] 2015-08-05 18:46
@hvelarde Nothing to do with developer/user point of view. I was just stating a fact that I ddin't know if it was ever implemented or there in 5.

**Closed by pbauer** 2015-08-05 18:45 UTC

**Comment by hvelarde** [comment] 2015-08-05 18:47
@pbauer great!
